//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Common.Entities;
    using QAMS.WEB.Entities;
    
    
    // Comment
    public interface IChangeControlRegistrationData
    {
        
        DataSet GetAllChangeControlRegistration(RequestContext requestContext);
        
        DataSet GetChangeControlRegistrationByChangeControlId(System.Int32? changeControlId);
        
        bool SaveChangeControlRegistration(ChangeControlRegistration changeControlRegistration);
        
        bool UpdateChangeControlRegistration(ChangeControlRegistration changeControlRegistration);
        
        bool DeleteChangeControlRegistrationByChangeControlId(System.Int32? changeControlId);
        
        bool DeleteAllChangeControlRegistration(List<int> changeControlIds);
    }
}
