//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class EquipmentConstants
    {
        
        public const string Id = "@Id_PSY";
        
        public const string Name = "@Name_PSY";
        
        public const string EquipmentId = "@EquipmentId_PSY";
        
        public const string Make = "@Make_PSY";
        
        public const string Model = "@Model_PSY";
        
        public const string SerialNumber = "@SerialNumber_PSY";
        
        public const string InstalledLocation = "@InstalledLocation_PSY";
        
        public const string DepartmentId = "@DepartmentId_PSY";
        
        public const string InstalledOn = "@InstalledOn_PSY";
        
        public const string WarrantyExpiresOn = "@WarrantyExpiresOn_PSY";
        
        public const string SuppliedBy = "@SuppliedBy_PSY";
        
        public const string Software = "@Software_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_Equipment_PSY_GET_ALL = "dbo.USP_Equipment_PSY_GET_ALL";
        
        public const string USP_Equipment_PSY_GET = "dbo.USP_Equipment_PSY_GET";
        
        public const string USP_Equipment_PSY_INSERT = "dbo.USP_Equipment_PSY_INSERT";
        
        public const string USP_Equipment_PSY_UPDATE = "dbo.USP_Equipment_PSY_UPDATE";
        
        public const string USP_Equipment_PSY_DELETE = "dbo.USP_Equipment_PSY_DELETE";
        
        public const string USP_Equipment_PSY_DELETE_ALL = "dbo.USP_Equipment_PSY_DELETE_ALL";
        
        public const string USP_QuickEquipment_INSERT = "dbo.USP_QuickEquipment_INSERT";
        
        public const string USP_QuickEquipment_UPDATE = "dbo.USP_QuickEquipment_UPDATE";
        
        public const string USP_Equipment_PSY_By_Id_GET = "dbo.USP_Equipment_PSY_By_Id_GET";
        
        public const string USP_Equipment_PSY_By_Id_DELETE = "dbo.USP_Equipment_PSY_By_Id_DELETE";
    }
}
