//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Common.Entities;
    using QAMS.WEB.Entities;
    
    
    // Comment
    public interface IChangeControlHodApprovalData
    {
        
        DataSet GetAllChangeControlHodApproval(RequestContext requestContext);
        
        DataSet GetChangeControlHodApprovalByChangeControlHodApprovalId(System.Int32? changeControlHodApprovalId);
        
        bool SaveChangeControlHodApproval(ChangeControlHodApproval changeControlHodApproval);
        
        bool UpdateChangeControlHodApproval(ChangeControlHodApproval changeControlHodApproval);
        
        bool DeleteChangeControlHodApprovalByChangeControlHodApprovalId(System.Int32? changeControlHodApprovalId);
        
        bool DeleteAllChangeControlHodApproval(List<int> changeControlHodApprovalIds);
        
        DataSet GetChangeControlHodApprovalByChangeControlRegistrationId(System.Int32? changeControlId);
        
        bool DeleteChangeControlHodApprovalByChangeControlRegistrationId(System.Int32? changeControlId);
    }
}
