//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Common.Entities;
    using QAMS.Entities;
    
    
    // Comment
    public interface IClosureData
    {
        
        DataSet GetAllClosure(RequestContext requestContext);
        
        DataSet GetClosureByCId(System.Int32? cId);
        
        bool SaveClosure(Closure closure);
        
        bool UpdateClosure(Closure closure);
        
        bool DeleteClosureByCId(System.Int32? cId);
        
        bool DeleteAllClosure(List<int> cIds);
    }
}
