//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Common.Entities;
    using QAMS.Entities;
    
    
    // Comment
    public interface IQADecisionData
    {
        
        DataSet GetAllQADecision(RequestContext requestContext);
        
        DataSet GetQADecisionByQADId(System.Int32? qADId);
        
        bool SaveQADecision(QADecision qADecision);
        
        bool UpdateQADecision(QADecision qADecision);
        
        bool DeleteQADecisionByQADId(System.Int32? qADId);
        
        bool DeleteAllQADecision(List<int> qADIds);
    }
}
