//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    using QAMS.Common.Entities;


    // Comment
    public class RoleMetadata
    {

        public int? Id { get; set; }
        public string Type { get; set; }

        public RoleGroup RoleGroup { get; set; }
        public RoleType RoleType { get; set; }      


       
    }

    public enum RoleType
    {
        ControlLoginInitiation = 1,
        HODReview = 2,
        QAReview = 3,
        CFTReview = 4,
        CustomerNotification = 5,
        QADecision = 6,
        ActionPlan = 7,
        FinalClosure = 8,
        ExtensionOfTargetDate = 9,
        WorkTransfer = 10,
        DossierPrint = 11,
        AuditTrials = 12,
        ReportsPrepared = 13
    }

    public enum RoleGroup
    {
        ChangeControls = 1,
        Deviations = 2,
        CPA = 3,
        SysytemManager = 4      
    }





}
