CREATE TRIGGER [trgAfterInsertInitiative]
	ON ChangeControlRegistration_PSY
	AFTER INSERT
	AS
	BEGIN
		SET NOCOUNT ON

		DECLARE @INITIATIVE_ID INT=0,@INITIATIVE VARCHAR(200),@CREATED_BY VARCHAR(100),@USER_ID INT=0;
		
		SELECT TOP(1) @INITIATIVE_ID=ChangeControlId_PSY,@INITIATIVE=Change_Type_PSY,@CREATED_BY=BR.CreatedBy_PSY,@USER_ID=USR.Id_PSY
		FROM ChangeControlRegistration_PSY BR JOIN User_PSY USR ON USR.UserId_PSY=@CREATED_BY ORDER BY ChangeControlId_PSY DESC;
		

		INSERT INTO INITIATIVE_AND_ACTIONPLANS_USERS_MAPPING(USER_ID,INIT_ID,ID_CTG,IS_ACTIONPLAN,IS_REVIEWED,IS_REJECT)
		SELECT @USER_ID,@INITIATIVE_ID,RM.ID_CTG,0,0,0 FROM ROLE_MAPPING RM 
		JOIN Role_PSY RLS ON RLS.Id_PSY=RM.ROLE_ID
		JOIN User_PSY USR ON USR.RoleId_PSY=RLS.Id_PSY
		WHERE USR.Id_PSY=@USER_ID

	END
GO
DISABLE TRIGGER [dbo].[trgAfterInsertInitiative]
    ON [dbo].[ChangeControlRegistration_PSY];


