//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Entities;
    using VAMLIbrary.Core.Extentions;
    using QAMS.Common.Entities;
    using QAMS.WEB.Services;


    // Comment
    public static class QADecisionConverter
    {
        
        public static List<QADecision> SetAllQADecision(DataSet dataset)
        {
            try
            {
                List<QADecision> result = new List<QADecision>();
                QADecision qADecisionData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        qADecisionData = new QADecision();
                        qADecisionData.InitiativeId = DatatypeConverter.SetIntValue(row[QADecisionConstants.InitiativeId.TrimAt()]);
                        qADecisionData.InitiativeName = Convert.ToString(row[QADecisionConstants.InitiativeName.TrimAt()]);
                        qADecisionData.IsSave = DatatypeConverter.SetBoolValue(row[QADecisionConstants.IsSave.TrimAt()]);
                        qADecisionData.Comments = Convert.ToString(row[QADecisionConstants.Comments.TrimAt()]);
                        qADecisionData.Status = Convert.ToString(row[QADecisionConstants.Status.TrimAt()]);
                        qADecisionData.CreatedBy = DatatypeConverter.SetIntValue(row[QADecisionConstants.CreatedBy.TrimAt()]);
                        qADecisionData.UpdatedBy = DatatypeConverter.SetIntValue(row[QADecisionConstants.UpdatedBy.TrimAt()]);
                        qADecisionData.CreatedDate = DatatypeConverter.SetDateTime(row[QADecisionConstants.CreatedDate.TrimAt()]);
                        qADecisionData.UpdatedDate = DatatypeConverter.SetDateTime(row[QADecisionConstants.UpdatedDate.TrimAt()]);
                        qADecisionData.Plant = DatatypeConverter.SetIntValue(row[QADecisionConstants.Plant.TrimAt()]);
                        qADecisionData.QADId = DatatypeConverter.SetIntValue(row[QADecisionConstants.QADId.TrimAt()]);
                        qADecisionData.IsReviewedActions = DatatypeConverter.SetBoolValue(row[QADecisionConstants.IsReviewedActions.TrimAt()]);
                        qADecisionData.Remarks = Convert.ToString(row[QADecisionConstants.Remarks.TrimAt()]);
                        qADecisionData.CNDocument = Convert.ToString(row[QADecisionConstants.CNDocument.TrimAt()]);
                        qADecisionData.ModifiedBy = Convert.ToString(row[QADecisionConstants.ModifiedBy.TrimAt()]);
                        qADecisionData.ModifiedDate = DatatypeConverter.SetDateTime(row[QADecisionConstants.ModifiedDate.TrimAt()]);
                        result.Add(qADecisionData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static QADecision SetQADecision(DataSet dataset)
        {
            var result = SetAllQADecision(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
