//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.WEB.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class ChangeControlRegistrationValidator
    {
        
        public static string IsValidChangeControlRegistration(ChangeControlRegistration changeControlRegistration)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(changeControlRegistration.ChangeControlUniqueCode, nameof(changeControlRegistration.ChangeControlUniqueCode)));
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlRegistration.ChangeControlUniqueCode,150, nameof(changeControlRegistration.ChangeControlUniqueCode)));
                validationMessages.Append(validationHelper.NullCheckValidator(changeControlRegistration.CreatedBy, nameof(changeControlRegistration.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlRegistration.CreatedBy,150, nameof(changeControlRegistration.CreatedBy)));
                validationMessages.Append(validationHelper.NullCheckValidator(changeControlRegistration.ModifiedBy, nameof(changeControlRegistration.ModifiedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlRegistration.ModifiedBy,150, nameof(changeControlRegistration.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
