//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using QAMS.Common.Entities;
    using QAMS.Entities;
    
    
    // Comment
    public interface IQAReviewService
    {
        
        ResponseContext<QAReview> GetAllQAReview(RequestContext requestContext);
        
        QAReview GetQAReviewByQAId(System.Int32? qAId);

        QAReview GetQAReviewByInitId(System.Int32? initId);

        bool SaveQAReview(QAReview qAReview);
        
        bool UpdateQAReview(QAReview qAReview);
        
        bool DeleteQAReviewByQAId(System.Int32? qAId);
        
        bool DeleteAllQAReview(List<int> qAIds);
    }
}
