//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    using QAMS.Common.Entities;
    
    
    // Comment
    public class ChangeContolActionPlan
    {
        
        private System.Int32? changecontolactionplanidField;
        
        private string typeField;
        
        private string descriptionField;
        
        private System.Int32? departmentidField;
        
        private System.Int32? assigneduserField;
        
        private System.Int32? assignedusergroupField;
        
        private DateTime? targetdateField;
        
        private string remarksField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public System.Int32? ChangeContolActionPlanId
        {
            get
            {
                return this.changecontolactionplanidField;
            }
            set
            {
                this.changecontolactionplanidField = value;
            }
        }
        
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        public System.Int32? DepartmentId
        {
            get
            {
                return this.departmentidField;
            }
            set
            {
                this.departmentidField = value;
            }
        }
        
        public System.Int32? AssignedUser
        {
            get
            {
                return this.assigneduserField;
            }
            set
            {
                this.assigneduserField = value;
            }
        }
        
        public System.Int32? AssignedUserGroup
        {
            get
            {
                return this.assignedusergroupField;
            }
            set
            {
                this.assignedusergroupField = value;
            }
        }
        
        public DateTime? TargetDate
        {
            get
            {
                return this.targetdateField;
            }
            set
            {
                this.targetdateField = value;
            }
        }
        
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
