//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class ChangeContolActionPlanConstants
    {
        
        public const string ChangeContolActionPlanId = "@ChangeContolActionPlanId_PSY";
        
        public const string Type = "@Type_PSY";
        
        public const string Description = "@Description_PSY";
        
        public const string DepartmentId = "@DepartmentId_PSY";
        
        public const string AssignedUser = "@AssignedUser_PSY";
        
        public const string AssignedUserGroup = "@AssignedUserGroup_PSY";
        
        public const string TargetDate = "@TargetDate_PSY";
        
        public const string Remarks = "@Remarks_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_ChangeContolActionPlan_PSY_GET_ALL = "dbo.USP_ChangeContolActionPlan_PSY_GET_ALL";
        
        public const string USP_ChangeContolActionPlan_PSY_GET = "dbo.USP_ChangeContolActionPlan_PSY_GET";
        
        public const string USP_ChangeContolActionPlan_PSY_INSERT = "dbo.USP_ChangeContolActionPlan_PSY_INSERT";
        
        public const string USP_ChangeContolActionPlan_PSY_UPDATE = "dbo.USP_ChangeContolActionPlan_PSY_UPDATE";
        
        public const string USP_ChangeContolActionPlan_PSY_DELETE = "dbo.USP_ChangeContolActionPlan_PSY_DELETE";
        
        public const string USP_ChangeContolActionPlan_PSY_DELETE_ALL = "dbo.USP_ChangeContolActionPlan_PSY_DELETE_ALL";
        
        public const string USP_QuickChangeContolActionPlan_INSERT = "dbo.USP_QuickChangeContolActionPlan_INSERT";
        
        public const string USP_QuickChangeContolActionPlan_UPDATE = "dbo.USP_QuickChangeContolActionPlan_UPDATE";
        
        public const string Id = "@Id_PSY";
        
        public const string USP_ChangeContolActionPlan_PSY_By_Id_GET = "dbo.USP_ChangeContolActionPlan_PSY_By_Id_GET";
        public const string USP_ActionPlan_PSY_GET_BY_INITD_AND_WORK_ID = "dbo.USP_ActionPlan_PSY_GET_BY_INITD_AND_WORK_ID";

        public const string USP_ChangeContolActionPlan_PSY_By_Id_DELETE = "dbo.USP_ChangeContolActionPlan_PSY_By_Id_DELETE";
    }
}
