//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class UserConstants
    {
        
        public const string Id = "@Id_PSY";
        
        public const string RoleId = "@RoleId_PSY";
        
        public const string UserId = "@UserId_PSY";
        
        public const string FirstName = "@FirstName_PSY";
        
        public const string Plants = "@Plants_PSY";
        
        public const string LastName = "@LastName_PSY";
        
        public const string DepartmentId = "@DepartmentId_PSY";


        
        public const string EmployeeId = "@EmployeeId_PSY";
        
        public const string EmailId = "@EmailId_PSY";
        
        public const string Password = "@Password_PSY";
        
        public const string IsActive = "@IsActive_PSY";
        
        public const string ForgotLoginPassword = "@ForgotLoginPassword_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_User_PSY_GET_ALL = "dbo.USP_User_PSY_GET_ALL";
        
        public const string USP_User_PSY_GET = "dbo.USP_User_PSY_GET";
        
        public const string USP_User_PSY_INSERT = "dbo.USP_User_PSY_INSERT";
        
        public const string USP_User_PSY_UPDATE = "dbo.USP_User_PSY_UPDATE";
        
        public const string USP_User_PSY_DELETE = "dbo.USP_User_PSY_DELETE";
        
        public const string USP_User_PSY_DELETE_ALL = "dbo.USP_User_PSY_DELETE_ALL";
        
        public const string USP_QuickUser_INSERT = "dbo.USP_QuickUser_INSERT";
        
        public const string USP_QuickUser_UPDATE = "dbo.USP_QuickUser_UPDATE";
        
        public const string USP_User_PSY_By_Id_GET = "dbo.USP_User_PSY_By_Id_GET";
        
        public const string USP_User_PSY_By_Id_DELETE = "dbo.USP_User_PSY_By_Id_DELETE";
    }
}
