//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class QualityEventValidator
    {
        
        public static string IsValidQualityEvent(QualityEvent qualityEvent)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(qualityEvent.Name, nameof(qualityEvent.Name)));
                validationMessages.Append(validationHelper.LengthCheckValidator(qualityEvent.Name,150, nameof(qualityEvent.Name)));
                validationMessages.Append(validationHelper.NullCheckValidator(qualityEvent.Code, nameof(qualityEvent.Code)));
                validationMessages.Append(validationHelper.LengthCheckValidator(qualityEvent.Code,150, nameof(qualityEvent.Code)));
                validationMessages.Append(validationHelper.NullCheckValidator(qualityEvent.CreatedBy, nameof(qualityEvent.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(qualityEvent.CreatedBy,150, nameof(qualityEvent.CreatedBy)));
                validationMessages.Append(validationHelper.NullCheckValidator(qualityEvent.ModifiedBy, nameof(qualityEvent.ModifiedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(qualityEvent.ModifiedBy,150, nameof(qualityEvent.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
