//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using QAMS.Common.Entities;
    using QAMS.Admin.Services;
    using QAMS.WEB.Entities;



    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/batchdetails")]
    public class BatchDetailsController : ControllerBase
    {
        
        private readonly IBatchDetailsService batchDetailsService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="batchDetailsService"></param>
        public BatchDetailsController(IBatchDetailsService batchDetailsService)
        {
            this.batchDetailsService = batchDetailsService;
        }
        
        /// <summary>
        /// This method is used to Get List of BatchDetails
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost()]
        public ActionResult<ResponseContext<BatchDetails>> GetAllBatchDetails(RequestContext requestContext)
        {
            var result = batchDetailsService.GetAllBatchDetails(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get BatchDetails By Id id
        /// </summary>
        /// <param name="id"></param>
        [HttpGet("{id}")]
        public ActionResult<BatchDetails> GetBatchDetailsById(System.Int32? id)
        {
            var result = batchDetailsService.GetBatchDetailsById(id);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save BatchDetails
        /// </summary>
        /// <param name="batchDetails"></param>
        [HttpPost("savebatchdetails")]
        public ActionResult<System.Boolean> SaveBatchDetails(BatchDetails batchDetails)
        {
            var result = batchDetailsService.SaveBatchDetails(batchDetails);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update BatchDetails
        /// </summary>
        /// <param name="batchDetails"></param>
        [HttpPost("updatebatchdetails")]
        public ActionResult<System.Boolean> UpdateBatchDetails(BatchDetails batchDetails)
        {
            var result = batchDetailsService.UpdateBatchDetails(batchDetails);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete BatchDetails By Id id
        /// </summary>
        /// <param name="id"></param>
        [HttpDelete("{id}")]
        public ActionResult<bool> DeleteBatchDetailsById(System.Int32? id)
        {
            var result = batchDetailsService.DeleteBatchDetailsById(id);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete BatchDetails By Multiple ids ids
        /// </summary>
        /// <param name="ids"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllBatchDetails(List<int> ids)
        {
            var result = batchDetailsService.DeleteAllBatchDetails(ids);
            return result;
        }
    }
}
