//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using QAMS.Common.Entities;
    using QAMS.Admin.Entities;
    using QAMS.Admin.Services;
    
    
    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/product")]
    public class ProductController : ControllerBase
    {
        
        private readonly IProductService productService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="productService"></param>
        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }
        
        /// <summary>
        /// This method is used to Get List of Product
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost("GetAllProduct")]
        public ActionResult<ResponseContext<Product>> GetAllProduct(RequestContext requestContext)
        {
            var result = productService.GetAllProduct(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get Product By Id id
        /// </summary>
        /// <param name="id"></param>
        [HttpGet("{id}")]
        public ActionResult<Product> GetProductById(System.Int32? id)
        {
            var result = productService.GetProductById(id);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save Product
        /// </summary>
        /// <param name="product"></param>
        [HttpPost("saveproduct")]
        public ActionResult<System.Boolean> SaveProduct(Product product)
        {
            var result = productService.SaveProduct(product);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update Product
        /// </summary>
        /// <param name="product"></param>
        [HttpPost("updateproduct")]
        public ActionResult<System.Boolean> UpdateProduct(Product product)
        {
            var result = productService.UpdateProduct(product);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete Product By Id id
        /// </summary>
        /// <param name="id"></param>
        [HttpDelete("{id}")]
        public ActionResult<bool> DeleteProductById(System.Int32? id)
        {
            var result = productService.DeleteProductById(id);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete Product By Multiple ids ids
        /// </summary>
        /// <param name="ids"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllProduct(List<int> ids)
        {
            var result = productService.DeleteAllProduct(ids);
            return result;
        }
    }
}
