//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class ChangeControlRegistrationConstants
    {
        
        public const string ChangeControlId = "@ChangeControlId_PSY";
        
        public const string ChangeControlUniqueCode = "@ChangeControlUniqueCode_PSY";
        
        public const string Reference = "@Reference_PSY";
        
        public const string ExternalReference = "@ExternalReference_PSY";
        
        public const string ReferenceDocuments = "@ReferenceDocuments_PSY";
        
        public const string QualityEvent = "@QualityEvent_PSY";
        
        public const string InitiatingDepartment = "@InitiatingDepartment_PSY";
        
        public const string TypeOfChange = "@TypeOfChange_PSY";
        
        public const string DateOfInitiation = "@DateOfInitiation_PSY";
        
        public const string TargetDateOfClosure = "@TargetDateOfClosure_PSY";
        
        public const string Market = "@Market_PSY";
        
        public const string Customer = "@Customer_PSY";
        
        public const string ChangeRelatedTo = "@ChangeRelatedTo_PSY";
        
        public const string BatchOrLotNumber = "@BatchOrLotNumber_PSY";
        
        public const string BatchOrLotDetail = "@BatchOrLotDetail_PSY";
        
        public const string Material = "@Material_PSY";
        
        public const string Equipment = "@Equipment_PSY";
        
        public const string DocumentDetails = "@DocumentDetails_PSY";
        
        public const string FacilityUtilityDetails = "@FacilityUtilityDetails_PSY";
        
        public const string ValidationDetails = "@ValidationDetails_PSY";
        
        public const string PackingDetails = "@PackingDetails_PSY";
        
        public const string SoftwareDetails = "@SoftwareDetails_PSY";
        
        public const string TestingDetails = "@TestingDetails_PSY";
        
        public const string SupplierServiceProviderDetails = "@SupplierServiceProviderDetails_PSY";
        
        public const string ProcessDetails = "@ProcessDetails_PSY";
        
        public const string OtherDetails = "@OtherDetails_PSY";
        
        public const string Product = "@Product_PSY";
        
        public const string ElementalImpuritiesAssesment = "@ElementalImpuritiesAssesment_PSY";
        
        public const string ElementalImpuritiesAssesmentReason = "@ElementalImpuritiesAssesmentReason_PSY";
        
        public const string NitrosamineImpuritiesAssesment = "@NitrosamineImpuritiesAssesment_PSY";
        
        public const string NitrosamineImpuritiesAssesmentReason = "@NitrosamineImpuritiesAssesmentReason_PSY";
        
        public const string GenotxicImpuritiesAssesment = "@GenotxicImpuritiesAssesment_PSY";
        
        public const string GenotxicImpuritiesAssesmentReason = "@GenotxicImpuritiesAssesmentReason_PSY";
        
        public const string ExistingProcedure = "@ExistingProcedure_PSY";
        
        public const string ProposedChange = "@ProposedChange_PSY";
        
        public const string JustificationForProposedChange = "@JustificationForProposedChange_PSY";
        
        public const string Documents = "@Documents_PSY";
        
        public const string DoesTheChangeImpactProductMaterialQuality = "@DoesTheChangeImpactProductMaterialQuality_PSY";
        
        public const string ImpactedProductMaterials = "@ImpactedProductMaterials_PSY";
        
        public const string AreAnyProceduresImpacted = "@AreAnyProceduresImpacted_PSY";
        
        public const string ImpactedProcedures = "@ImpactedProcedures_PSY";
        
        public const string Comments = "@Comments_PSY";
        
        public const string Registeredby = "@Registeredby_PSY";
        
        public const string Reintiate = "@Reintiate_PSY";
        
        public const string Status = "@Status_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";

        public const string CategoryName = "@CategoryName_PSY";

        public const string CategoryId = "@CATID_PSY";

        public const string USP_ChangeControlRegistration_PSY_GET_ALL = "dbo.USP_ChangeControlRegistration_PSY_GET_ALL";
        
        public const string USP_ChangeControlRegistration_PSY_GET = "dbo.USP_ChangeControlRegistration_PSY_GET";
        
        public const string USP_ChangeControlRegistration_PSY_INSERT = "dbo.USP_ChangeControlRegistration_PSY_INSERT";
        
        public const string USP_ChangeControlRegistration_PSY_UPDATE = "dbo.USP_ChangeControlRegistration_PSY_UPDATE";
        
        public const string USP_ChangeControlRegistration_PSY_DELETE = "dbo.USP_ChangeControlRegistration_PSY_DELETE";
        
        public const string USP_ChangeControlRegistration_PSY_DELETE_ALL = "dbo.USP_ChangeControlRegistration_PSY_DELETE_ALL";
        
        public const string USP_QuickChangeControlRegistration_INSERT = "dbo.USP_QuickChangeControlRegistration_INSERT";
        
        public const string USP_QuickChangeControlRegistration_UPDATE = "dbo.USP_QuickChangeControlRegistration_UPDATE";
    }
}
