//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Entities
{
    using System;
    
    public class DeviationsRegistration : BaseEntity
    {
        
        private System.Int32? deviationidField;
        
        private string deviationUniquecodeField;

        private DateTime? dateofOccuranceField;
        
        private DateTime? dateofidentificationField;
        
        private string stageField;
        
        private string systemField;
        
        private string deviationdetailsField;
        
        public System.Int32? DeviationId
        {
            get
            {
                return this.deviationidField;
            }
            set
            {
                this.deviationidField = value;
            }
        }        
        public string DeviationUniqueCode
        {
            get
            {
                return this.deviationUniquecodeField;
            }
            set
            {
                this.deviationUniquecodeField = value;
            }
        }
        public DateTime? DateOfOccurance
        {
            get
            {
                return this.dateofOccuranceField;
            }
            set
            {
                this.dateofOccuranceField = value;
            }
        }
        public DateTime? DateOfIdentification
        {
            get
            {
                return this.dateofidentificationField;
            }
            set
            {
                this.dateofidentificationField = value;
            }
        }
        public string Stage
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
            }
        }
        public string System
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }
        public string DeviationDetails
        {
            get
            {
                return this.deviationdetailsField;
            }
            set
            {
                this.deviationdetailsField = value;
            }
        }
    }
}
