//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class RoleValidator
    {
        
        public static string IsValidRole(Role role)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(role.Name, nameof(role.Name)));
                validationMessages.Append(validationHelper.LengthCheckValidator(role.Name,150, nameof(role.Name)));
                validationMessages.Append(validationHelper.NullCheckValidator(role.Description, nameof(role.Description)));
                validationMessages.Append(validationHelper.LengthCheckValidator(role.Description,150, nameof(role.Description)));
                validationMessages.Append(validationHelper.NullCheckValidator(role.CreatedBy, nameof(role.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(role.CreatedBy,150, nameof(role.CreatedBy)));
                validationMessages.Append(validationHelper.NullCheckValidator(role.ModifiedBy, nameof(role.ModifiedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(role.ModifiedBy,150, nameof(role.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
