//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Validators;


    // Comment
    public static class RoleValidator
    {

        public static string IsValidRole(Role role)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(role.name, nameof(role.name)));
                validationMessages.Append(validationHelper.LengthCheckValidator(role.name, 150, nameof(role.name)));
                validationMessages.Append(validationHelper.NullCheckValidator(role.description, nameof(role.description)));
                validationMessages.Append(validationHelper.LengthCheckValidator(role.description, 150, nameof(role.description)));
                validationMessages.Append(validationHelper.NullCheckValidator(role.createdBy, nameof(role.createdBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(role.createdBy, 150, nameof(role.createdBy)));
                // validationMessages.Append(validationHelper.NullCheckValidator(role.modifiedBy, nameof(role.modifiedBy)));
                // validationMessages.Append(validationHelper.LengthCheckValidator(role.modifiedBy,150, nameof(role.modifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','), 1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
