CREATE TABLE [dbo].[ChangeControlRegistration_PSY] (
    [ChangeControlId_PSY]                           INT             IDENTITY (1, 1) NOT NULL,
    [ChangeControlUniqueCode_PSY]                   NVARCHAR (150)  NOT NULL,
    [Reference_PSY]                                 BIT             NULL,
    [ExternalReference_PSY]                         NVARCHAR (250)  NULL,
    [ReferenceDocuments_PSY]                        NVARCHAR (MAX)  NULL,
    [QualityEvent_PSY]                              INT             NULL,
    [InitiatingDepartment_PSY]                      INT             NULL,
    [TypeOfChange_PSY]                              BIT             NULL,
    [DateOfInitiation_PSY]                          DATETIME        NULL,
    [TargetDateOfClosure_PSY]                       DATETIME        NULL,
    [Market_PSY]                                    INT             NULL,
    [Customer_PSY]                                  INT             NULL,
    [ChangeRelatedTo_PSY]                           INT             NULL,
    [BatchOrLotNumber_PSY]                          INT             NULL,
    [BatchOrLotDetail_PSY]                          NVARCHAR (250)  NULL,
    [Material_PSY]                                  INT             NULL,
    [Equipment_PSY]                                 INT             NULL,
    [DocumentDetails_PSY]                           NVARCHAR (250)  NULL,
    [FacilityUtilityDetails_PSY]                    NVARCHAR (250)  NULL,
    [ValidationDetails_PSY]                         NVARCHAR (250)  NULL,
    [PackingDetails_PSY]                            NVARCHAR (250)  NULL,
    [SoftwareDetails_PSY]                           NVARCHAR (250)  NULL,
    [TestingDetails_PSY]                            NVARCHAR (250)  NULL,
    [SupplierServiceProviderDetails_PSY]            NVARCHAR (250)  NULL,
    [ProcessDetails_PSY]                            NVARCHAR (250)  NULL,
    [OtherDetails_PSY]                              NVARCHAR (250)  NULL,
    [Product_PSY]                                   INT             NULL,
    [ElementalImpuritiesAssesment_PSY]              BIT             NULL,
    [ElementalImpuritiesAssesmentReason_PSY]        NVARCHAR (250)  NOT NULL,
    [NitrosamineImpuritiesAssesment_PSY]            BIT             NULL,
    [NitrosamineImpuritiesAssesmentReason_PSY]      NVARCHAR (250)  NULL,
    [GenotxicImpuritiesAssesment_PSY]               BIT             NULL,
    [GenotxicImpuritiesAssesmentReason_PSY]         NVARCHAR (250)  NULL,
    [ExistingProcedure_PSY]                         NVARCHAR (2000) NOT NULL,
    [ProposedChange_PSY]                            NVARCHAR (2000) NOT NULL,
    [JustificationForProposedChange_PSY]            NVARCHAR (2000) NOT NULL,
    [Documents_PSY]                                 NVARCHAR (MAX)  NOT NULL,
    [DoesTheChangeImpactProductMaterialQuality_PSY] BIT             NULL,
    [ImpactedProductMaterials_PSY]                  INT             NULL,
    [AreAnyProceduresImpacted_PSY]                  BIT             NULL,
    [ImpactedProcedures_PSY]                        INT             NULL,
    [Comments_PSY]                                  NVARCHAR (250)  NOT NULL,
    [Registeredby_PSY]                              INT             NULL,
    [Reintiate_PSY]                                 BIT             NULL,
    [Status_PSY]                                    INT             NULL,
    [CreatedBy_PSY]                                 NVARCHAR (150)  NOT NULL,
    [CreatedDate_PSY]                               DATETIME        NULL,
    [ModifiedBy_PSY]                                NVARCHAR (150)  NOT NULL,
    [ModifiedDate_PSY]                              DATETIME        NULL,
    [Document]                                      NVARCHAR (MAX)  NULL,
    [ChangeDetails_PSY]                             NVARCHAR (MAX)  NULL,
    [RequestDetails_PSY]                            NVARCHAR (MAX)  NULL,
    [ImpactDetails_PSY]                             NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_ChangeControlRegistration_PSY] PRIMARY KEY CLUSTERED ([ChangeControlId_PSY] ASC),
    UNIQUE NONCLUSTERED ([ChangeControlUniqueCode_PSY] ASC)
);



