CREATE TABLE [dbo].[FunctionalProfile_PSY] (
    [Id_PSY]                            INT            IDENTITY (1, 1) NOT NULL,
    [RoleId_PSY]                        INT            NULL,
    [ChangeControlInitiation_PSY]       BIT            NULL,
    [CCHODReview_PSY]                   BIT            NULL,
    [CCQAReview_PSY]                    BIT            NULL,
    [CCCFTReview_PSY]                   BIT            NULL,
    [CCCustomerNotification_PSY]        BIT            NULL,
    [CCQADecision_PSY]                  BIT            NULL,
    [CCActionPlan_PSY]                  BIT            NULL,
    [CCFinalClosure_PSY]                BIT            NULL,
    [CCExtensionOfTargetDate_PSY]       BIT            NULL,
    [CCWorkTransfer_PSY]                BIT            NULL,
    [CCDossierPrint_PSY]                BIT            NULL,
    [CCAuditTrial_PSY]                  BIT            NULL,
    [CCReport_PSY]                      BIT            NULL,
    [DeviationInitiation_PSY]           BIT            NULL,
    [DIHODReview_PSY]                   BIT            NULL,
    [DIQAReview_PSY]                    BIT            NULL,
    [DICFTReview_PSY]                   BIT            NULL,
    [DICustomerNotification_PSY]        BIT            NULL,
    [QAManager_PSY]                     BIT            NULL,
    [Investigation_PSY]                 BIT            NULL,
    [DIQADecision_PSY]                  BIT            NULL,
    [DIActionPlan_PSY]                  BIT            NULL,
    [DIFinalClosure_PSY]                BIT            NULL,
    [DIExtensionOfTargetDate_PSY]       BIT            NULL,
    [DIWorkTransfer_PSY]                BIT            NULL,
    [DIDossierPrint_PSY]                BIT            NULL,
    [DIAuditTrial_PSY]                  BIT            NULL,
    [DIReport_PSY]                      BIT            NULL,
    [CAPAInitiation_PSY]                BIT            NULL,
    [CAPAHODReview_PSY]                 BIT            NULL,
    [CAPAQAReview_PSY]                  BIT            NULL,
    [CAPACFTReview_PSY]                 BIT            NULL,
    [CAPAQADecision_PSY]                BIT            NULL,
    [CAPAActionPlan_PSY]                BIT            NULL,
    [CAPAFinalClosure_PSY]              BIT            NULL,
    [CAPAExtensionOfTargetDate_PSY]     BIT            NULL,
    [CAPAWorkTransfer_PSY]              BIT            NULL,
    [CAPADossierPrint_PSY]              BIT            NULL,
    [CAPAAuditTrial_PSY]                BIT            NULL,
    [CAPAReport_PSY]                    BIT            NULL,
    [SecuritySetting_PSY]               BIT            NULL,
    [NewRole_PSY]                       BIT            NULL,
    [SetFunctionalProfile_PSY]          BIT            NULL,
    [NewUser_PSY]                       BIT            NULL,
    [NewUserApproval_PSY]               BIT            NULL,
    [PlantAssignment_PSY]               BIT            NULL,
    [ModifyPlantAssignment_PSY]         BIT            NULL,
    [UserGroup_PSY]                     BIT            NULL,
    [ModifyUserGroup_PSY]               BIT            NULL,
    [UserAccountStatus_PSY]             BIT            NULL,
    [ResetLoginPassword_PSY]            BIT            NULL,
    [ModifyUser_PSY]                    BIT            NULL,
    [ProductOrMaterialRegistration_PSY] BIT            NULL,
    [BatchOrLotParticulars_PSY]         BIT            NULL,
    [EquipmentRegistration_PSY]         BIT            NULL,
    [MarketRegistration_PSY]            BIT            NULL,
    [CustomerRegistration_PSY]          BIT            NULL,
    [AuditTrial_PSY]                    BIT            NULL,
    [Remark_PSY]                        NVARCHAR (150) NULL,
    [CreatedBy_PSY]                     NVARCHAR (150) NOT NULL,
    [CreatedDate_PSY]                   DATETIME       NULL,
    [ModifiedBy_PSY]                    NVARCHAR (150) NOT NULL,
    [ModifiedDate_PSY]                  DATETIME       NULL,
    CONSTRAINT [PK_FunctionalProfile_PSY] PRIMARY KEY CLUSTERED ([Id_PSY] ASC),
    CONSTRAINT [FK_FunctionalProfile_PSY_Id_PSY_Role_PSY_RoleId_PSY] FOREIGN KEY ([RoleId_PSY]) REFERENCES [dbo].[Role_PSY] ([Id_PSY])
);

