CREATE TABLE [dbo].[INITIATIVE_AND_ACTIONPLANS_USERS_MAPPING]
(
	[ID_IM] INT NOT NULL PRIMARY KEY IDENTITY, 
    [USER_ID] INT NULL, 
    [ID_CTG] INT NULL, 
    [IS_REVIEWED] BIT NULL, 
    [IS_ACTIONPLAN] BIT NULL, 
    [INIT_ID] INT NULL, 
    [IS_REJECT] BIT NULL, 
    [DOCUMENT_ACTION] XML NULL, 
    [DOCUMENT_CTG] XML NULL
)
