CREATE TABLE [dbo].[INITIATIVE_WORKFLOW_PSY]
(
	[WORKFLOW_ID] INT NOT NULL PRIMARY KEY, 
    [INITIATIVE_ID] INT NULL, 
    [INITIATIVE_TYPE] VARCHAR(50) NULL, 
    [STAGE] VARCHAR(50) NULL, 
    [STAGE_ID] INT NULL, 
    [CREATED_BY] VARCHAR(100) NULL, 
    [UPDATED_BY] VARCHAR(100) NULL, 
    [CREATED_DATE] DATETIME NULL, 
    [UPDATED_DATE] DATETIME NULL, 
    [ISCOMPLETED] BIT NULL, 
    [STATUS] VARCHAR(50) NULL
)
