CREATE TABLE [dbo].[WORKFLOW_ACTION_PLAN_USERS_MAPPING]
(
	[ACTION_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [USER_ID] INT NULL, 
    [USER_NAME] VARCHAR(200) NULL, 
    [WORKFLOW_ID] INT NULL, 
    [WORKFLOW_TYPE] VARCHAR(50) NULL, 
    [CREATED_BY] VARCHAR(100) NULL, 
    [UPDATED_BY] VARCHAR(100) NULL, 
    [CREATED_DATE] DATETIME NULL, 
    [UPDATED_DATE] DATETIME NULL, 
    [STATUS] VARCHAR(100) NULL, 
    [IS_REVIEWED] BIT NULL, 
    [IS_ACTIONPLAN] BIT NULL
)
