//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.WEB.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class ChangeControlHodApprovalValidator
    {
        
        public static string IsValidChangeControlHodApproval(ChangeControlHodApproval changeControlHodApproval)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlHodApproval.ProposedActionPlans,150, nameof(changeControlHodApproval.ProposedActionPlans)));
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlHodApproval.HodReviewComments,2000, nameof(changeControlHodApproval.HodReviewComments)));
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlHodApproval.Remarks,250, nameof(changeControlHodApproval.Remarks)));
                validationMessages.Append(validationHelper.NullCheckValidator(changeControlHodApproval.CreatedBy, nameof(changeControlHodApproval.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlHodApproval.CreatedBy,150, nameof(changeControlHodApproval.CreatedBy)));
                validationMessages.Append(validationHelper.NullCheckValidator(changeControlHodApproval.ModifiedBy, nameof(changeControlHodApproval.ModifiedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(changeControlHodApproval.ModifiedBy,150, nameof(changeControlHodApproval.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
