//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Entities
{
    using System;
    using System.Collections.Generic;
    using QAMS.Common.Entities;
    
    
    // Comment
    public class Closure
    {
        
        private System.Int32? initiativeidField;
        
        private string initiativenameField;
        
        private System.Boolean? issaveField;
        
        private string implementeffchangesField;
        
        private string statusField;
        
        private System.Int32? createdbyField;
        
        private System.Int32? updatedbyField;
        
        private DateTime? createddateField;
        
        private DateTime? updateddateField;
        
        private System.Int32? plantField;
        
        private System.Int32? cidField;
        
        private string decisionField;
        
        private string remarksField;
        
        private string actionplanreviewcommentsField;
        
        private System.Boolean? isalldocumentsapprovedeffField;
        
        private System.Boolean? trainingcompletedField;
        
        private System.Boolean? isapprovedchangeseffField;
        
        private System.Boolean? isidentifiedactionsField;
        
        private string cdocumentField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public System.Int32? InitiativeId
        {
            get
            {
                return this.initiativeidField;
            }
            set
            {
                this.initiativeidField = value;
            }
        }
        
        public string InitiativeName
        {
            get
            {
                return this.initiativenameField;
            }
            set
            {
                this.initiativenameField = value;
            }
        }
        
        public System.Boolean? IsSave
        {
            get
            {
                return this.issaveField;
            }
            set
            {
                this.issaveField = value;
            }
        }
        
        public string ImplementEffChanges
        {
            get
            {
                return this.implementeffchangesField;
            }
            set
            {
                this.implementeffchangesField = value;
            }
        }
        
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        public System.Int32? CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public System.Int32? UpdatedBy
        {
            get
            {
                return this.updatedbyField;
            }
            set
            {
                this.updatedbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public DateTime? UpdatedDate
        {
            get
            {
                return this.updateddateField;
            }
            set
            {
                this.updateddateField = value;
            }
        }
        
        public System.Int32? Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }
        
        public System.Int32? CId
        {
            get
            {
                return this.cidField;
            }
            set
            {
                this.cidField = value;
            }
        }
        
        public string Decision
        {
            get
            {
                return this.decisionField;
            }
            set
            {
                this.decisionField = value;
            }
        }
        
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        public string ActionPlanReviewComments
        {
            get
            {
                return this.actionplanreviewcommentsField;
            }
            set
            {
                this.actionplanreviewcommentsField = value;
            }
        }
        
        public System.Boolean? IsAllDocumentsApprovedEff
        {
            get
            {
                return this.isalldocumentsapprovedeffField;
            }
            set
            {
                this.isalldocumentsapprovedeffField = value;
            }
        }
        
        public System.Boolean? TrainingCompleted
        {
            get
            {
                return this.trainingcompletedField;
            }
            set
            {
                this.trainingcompletedField = value;
            }
        }
        
        public System.Boolean? IsApprovedChangesEff
        {
            get
            {
                return this.isapprovedchangeseffField;
            }
            set
            {
                this.isapprovedchangeseffField = value;
            }
        }
        
        public System.Boolean? IsIdentifiedActions
        {
            get
            {
                return this.isidentifiedactionsField;
            }
            set
            {
                this.isidentifiedactionsField = value;
            }
        }
        
        public string CDocument
        {
            get
            {
                return this.cdocumentField;
            }
            set
            {
                this.cdocumentField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
