//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Entities
{
    using System;


    // Comment
    public class BatchDetails
    {

       

        public System.Int32? Id { get; set; }
      

        public string BatchId { get; set; }

        public string batchType { get; set; }


        public string productMaterial { get; set; }

        public string batchLotNo { get; set; }

        public string batchLotSize { get; set; }

        public string manufacturingDate { get; set; }





        public string arno { get; set; }
      

        public string InitiatedBy { get; set; }
       

        public DateTime? InitiatedOn { get; set; }
      

        public string CreatedBy { get; set; }
     

        public DateTime? CreatedDate { get; set; }
     
        public string otherDetails { get; set; }
        public string ModifiedBy { get; set; }
       
        public DateTime? ModifiedDate { get; set; }
      
    }
}
