//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class BatchDetailsConstants
    {
        
        public const string Id = "@Id_PSY";
        
        public const string BatchId = "@BatchId_PSY";
        
        public const string Material = "@Material_PSY";
        
        public const string ARNumber = "@ARNumber_PSY";
        
        public const string InitiatedBy = "@InitiatedBy_PSY";
        
        public const string InitiatedOn = "@InitiatedOn_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_BatchDetails_PSY_GET_ALL = "dbo.USP_BatchDetails_PSY_GET_ALL";
        
        public const string USP_BatchDetails_PSY_GET = "dbo.USP_BatchDetails_PSY_GET";
        
        public const string USP_BatchDetails_PSY_INSERT = "dbo.USP_BatchDetails_PSY_INSERT";
        
        public const string USP_BatchDetails_PSY_UPDATE = "dbo.USP_BatchDetails_PSY_UPDATE";
        
        public const string USP_BatchDetails_PSY_DELETE = "dbo.USP_BatchDetails_PSY_DELETE";
        
        public const string USP_BatchDetails_PSY_DELETE_ALL = "dbo.USP_BatchDetails_PSY_DELETE_ALL";
        
        public const string USP_QuickBatchDetails_INSERT = "dbo.USP_QuickBatchDetails_INSERT";
        
        public const string USP_QuickBatchDetails_UPDATE = "dbo.USP_QuickBatchDetails_UPDATE";
    }
}
