//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    using QAMS.Common.Entities;
    
    
    // Comment
    public class ChangeContolQaApproval
    {
        
        private System.Int32? changecontolqaapprovalidField;
        
        private System.Int32? changecontrolidField;
        
        private System.Boolean? classificationofchangeField;
        
        private System.Boolean? impactonproceduresordrawingsorassociatedformatsField;
        
        private string proceduresordrawingsorassociatedformatsimpactedasresultofchangeField;
        
        private System.Boolean? arethereanyregulatorycustomercommitmentsimpactedbythischangeField;
        
        private string impactedregulatorycustomercommitmentsField;
        
        private System.Boolean? additionalactionplanproposalsrequiredField;
        
        private string proposedadditionalactionplansField;
        
        private System.Boolean? riskassesmentrequiredField;
        
        private System.Int32? proposedriskassesmentField;
        
        private System.Int32? customerapprovalField;
        
        private System.Int32? departmentsrequiredtoprovideimpactassesmentevaluationField;
        
        private string qareviewcommentsField;
        
        private string documentsField;
        
        private string remarksField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public System.Int32? ChangeContolQaApprovalId
        {
            get
            {
                return this.changecontolqaapprovalidField;
            }
            set
            {
                this.changecontolqaapprovalidField = value;
            }
        }
        
        public System.Int32? ChangeControlId
        {
            get
            {
                return this.changecontrolidField;
            }
            set
            {
                this.changecontrolidField = value;
            }
        }
        
        public System.Boolean? ClassificationOfChange
        {
            get
            {
                return this.classificationofchangeField;
            }
            set
            {
                this.classificationofchangeField = value;
            }
        }
        
        public System.Boolean? ImpactOnProceduresOrDrawingsOrAssociatedFormats
        {
            get
            {
                return this.impactonproceduresordrawingsorassociatedformatsField;
            }
            set
            {
                this.impactonproceduresordrawingsorassociatedformatsField = value;
            }
        }
        
        public string ProceduresOrDrawingsOrAssociatedFormatsImpactedAsResultOfChange
        {
            get
            {
                return this.proceduresordrawingsorassociatedformatsimpactedasresultofchangeField;
            }
            set
            {
                this.proceduresordrawingsorassociatedformatsimpactedasresultofchangeField = value;
            }
        }
        
        public System.Boolean? AreThereAnyRegulatoryCustomerCommitmentsImpactedByThisChange
        {
            get
            {
                return this.arethereanyregulatorycustomercommitmentsimpactedbythischangeField;
            }
            set
            {
                this.arethereanyregulatorycustomercommitmentsimpactedbythischangeField = value;
            }
        }
        
        public string ImpactedRegulatoryCustomerCommitments
        {
            get
            {
                return this.impactedregulatorycustomercommitmentsField;
            }
            set
            {
                this.impactedregulatorycustomercommitmentsField = value;
            }
        }
        
        public System.Boolean? AdditionalActionPlanProposalsRequired
        {
            get
            {
                return this.additionalactionplanproposalsrequiredField;
            }
            set
            {
                this.additionalactionplanproposalsrequiredField = value;
            }
        }
        
        public string ProposedAdditionalActionPlans
        {
            get
            {
                return this.proposedadditionalactionplansField;
            }
            set
            {
                this.proposedadditionalactionplansField = value;
            }
        }
        
        public System.Boolean? RiskAssesmentRequired
        {
            get
            {
                return this.riskassesmentrequiredField;
            }
            set
            {
                this.riskassesmentrequiredField = value;
            }
        }
        
        public System.Int32? ProposedRiskAssesment
        {
            get
            {
                return this.proposedriskassesmentField;
            }
            set
            {
                this.proposedriskassesmentField = value;
            }
        }
        
        public System.Int32? CustomerApproval
        {
            get
            {
                return this.customerapprovalField;
            }
            set
            {
                this.customerapprovalField = value;
            }
        }
        
        public System.Int32? DepartmentsRequiredToProvideImpactAssesmentEvaluation
        {
            get
            {
                return this.departmentsrequiredtoprovideimpactassesmentevaluationField;
            }
            set
            {
                this.departmentsrequiredtoprovideimpactassesmentevaluationField = value;
            }
        }
        
        public string QAReviewComments
        {
            get
            {
                return this.qareviewcommentsField;
            }
            set
            {
                this.qareviewcommentsField = value;
            }
        }
        
        public string Documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
        
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
