//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class ChangeContolQaApprovalConstants
    {
        
        public const string ChangeContolQaApprovalId = "@ChangeContolQaApprovalId_PSY";
        
        public const string ChangeControlId = "@ChangeControlId_PSY";
        
        public const string ClassificationOfChange = "@ClassificationOfChange_PSY";
        
        public const string ImpactOnProceduresOrDrawingsOrAssociatedFormats = "@ImpactOnProceduresOrDrawingsOrAssociatedFormats_PSY";
        
        public const string ProceduresOrDrawingsOrAssociatedFormatsImpactedAsResultOfChange = "@ProceduresOrDrawingsOrAssociatedFormatsImpactedAsResultOfChange_PSY";
        
        public const string AreThereAnyRegulatoryCustomerCommitmentsImpactedByThisChange = "@AreThereAnyRegulatoryCustomerCommitmentsImpactedByThisChange_PSY";
        
        public const string ImpactedRegulatoryCustomerCommitments = "@ImpactedRegulatoryCustomerCommitments_PSY";
        
        public const string AdditionalActionPlanProposalsRequired = "@AdditionalActionPlanProposalsRequired_PSY";
        
        public const string ProposedAdditionalActionPlans = "@ProposedAdditionalActionPlans_PSY";
        
        public const string RiskAssesmentRequired = "@RiskAssesmentRequired_PSY";
        
        public const string ProposedRiskAssesment = "@ProposedRiskAssesment_PSY";
        
        public const string CustomerApproval = "@CustomerApproval_PSY";
        
        public const string DepartmentsRequiredToProvideImpactAssesmentEvaluation = "@DepartmentsRequiredToProvideImpactAssesmentEvaluation_PSY";
        
        public const string QAReviewComments = "@QAReviewComments_PSY";
        
        public const string Documents = "@Documents_PSY";
        
        public const string Remarks = "@Remarks_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_ChangeContolQaApproval_PSY_GET_ALL = "dbo.USP_ChangeContolQaApproval_PSY_GET_ALL";
        
        public const string USP_ChangeContolQaApproval_PSY_GET = "dbo.USP_ChangeContolQaApproval_PSY_GET";
        
        public const string USP_ChangeContolQaApproval_PSY_INSERT = "dbo.USP_ChangeContolQaApproval_PSY_INSERT";
        
        public const string USP_ChangeContolQaApproval_PSY_UPDATE = "dbo.USP_ChangeContolQaApproval_PSY_UPDATE";
        
        public const string USP_ChangeContolQaApproval_PSY_DELETE = "dbo.USP_ChangeContolQaApproval_PSY_DELETE";
        
        public const string USP_ChangeContolQaApproval_PSY_DELETE_ALL = "dbo.USP_ChangeContolQaApproval_PSY_DELETE_ALL";
        
        public const string USP_QuickChangeContolQaApproval_INSERT = "dbo.USP_QuickChangeContolQaApproval_INSERT";
        
        public const string USP_QuickChangeContolQaApproval_UPDATE = "dbo.USP_QuickChangeContolQaApproval_UPDATE";
        
        public const string USP_ChangeContolQaApproval_PSY_By_ChangeControlId_GET = "dbo.USP_ChangeContolQaApproval_PSY_By_ChangeControlId_GET";
        
        public const string USP_ChangeContolQaApproval_PSY_By_ChangeControlId_DELETE = "dbo.USP_ChangeContolQaApproval_PSY_By_ChangeControlId_DELETE";
    }
}
