//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using QAMS.Common.Entities;
    using QAMS.Admin.Entities;
    using QAMS.WEB.Entities;


    // Comment
    public interface IBatchDetailsService
    {
        
        ResponseContext<BatchDetails> GetAllBatchDetails(RequestContext requestContext);
        
        BatchDetails GetBatchDetailsById(System.Int32? id);
        
        bool SaveBatchDetails(BatchDetails batchDetails);
        
        bool UpdateBatchDetails(BatchDetails batchDetails);
        
        bool DeleteBatchDetailsById(System.Int32? id);
        
        bool DeleteAllBatchDetails(List<int> ids);
    }
}
