//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Common.Entities;
    using QAMS.Admin.Entities;
    using VAMLibrary.Core;
    using VAMLibrary.Core.Common;
    
    
    // Comment
    public class QualityEventData : IQualityEventData
    {
        
        private readonly DataAccessHelper dataAccessHelper;
        
        public QualityEventData(DataAccessHelper dataAccessHelper)
        {
            this.dataAccessHelper = dataAccessHelper;
        }
        
        public DataSet GetAllQualityEvent(RequestContext requestContext)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = RequestContextConstants.PageNumber, Value = requestContext.PageNumber });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = RequestContextConstants.PageSize, Value = requestContext.PageSize });
                DataSet dataset = (DataSet)dataAccessHelper.ExecuteStoredProcedure(QualityEventConstants.USP_QualityEvent_PSY_GET_ALL, sqlparms, ExecutionType.Dataset);
                return dataset;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public DataSet GetQualityEventById(System.Int32? id)
        {
            try
            {
                DataSet dataset = (DataSet)dataAccessHelper.ExecuteStoredProcedure(QualityEventConstants.USP_QualityEvent_PSY_GET, QualityEventConstants.Id, DbType.Int32, id, ExecutionType.Dataset);
                return dataset;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool SaveQualityEvent(QualityEvent qualityEvent)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = QualityEventConstants.Name, Value = qualityEvent.Name });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = QualityEventConstants.Code, Value = qualityEvent.Code });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = QualityEventConstants.CreatedBy, Value = qualityEvent.CreatedBy });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = QualityEventConstants.ModifiedBy, Value = qualityEvent.ModifiedBy });
                Object result = dataAccessHelper.ExecuteStoredProcedure(QualityEventConstants.USP_QualityEvent_PSY_INSERT, sqlparms, ExecutionType.Scalar);
                return (Convert.ToInt32(result) > 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool UpdateQualityEvent(QualityEvent qualityEvent)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = QualityEventConstants.Id, Value = qualityEvent.Id });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = QualityEventConstants.Name, Value = qualityEvent.Name });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = QualityEventConstants.Code, Value = qualityEvent.Code });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = QualityEventConstants.ModifiedBy, Value = qualityEvent.ModifiedBy });
                Object result = dataAccessHelper.ExecuteStoredProcedure(QualityEventConstants.USP_QualityEvent_PSY_UPDATE, sqlparms, ExecutionType.Scalar);
                return (Convert.ToInt32(result) > 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteQualityEventById(System.Int32? id)
        {
            try
            {
                var result = dataAccessHelper.ExecuteStoredProcedure(QualityEventConstants.USP_QualityEvent_PSY_DELETE, QualityEventConstants.Id, DbType.Int32, id, ExecutionType.NonQuery);
                return (Convert.ToInt32(result) >= 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllQualityEvent(List<int> ids)
        {
            try
            {
                var result = dataAccessHelper.ExecuteStoredProcedure(QualityEventConstants.USP_QualityEvent_PSY_DELETE_ALL, QualityEventConstants.Id, DbType.String, string.Join(',',  ids), ExecutionType.NonQuery);
                return (Convert.ToInt32(result) >= 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
