//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using QAMS.Common.Entities;
    using QAMS.Entities;
    using QAMS.Sheet1.Services;
    
    
    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/actionplanreview")]
    public class ActionPlanReviewController : ControllerBase
    {
        
        private readonly IActionPlanReviewService actionPlanReviewService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="actionPlanReviewService"></param>
        public ActionPlanReviewController(IActionPlanReviewService actionPlanReviewService)
        {
            this.actionPlanReviewService = actionPlanReviewService;
        }
        
        /// <summary>
        /// This method is used to Get List of ActionPlanReview
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost()]
        public ActionResult<ResponseContext<ActionPlanReview>> GetAllActionPlanReview(RequestContext requestContext)
        {
            var result = actionPlanReviewService.GetAllActionPlanReview(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get ActionPlanReview By Id aPId
        /// </summary>
        /// <param name="aPId"></param>
        [HttpGet("{aPId}")]
        public ActionResult<ActionPlanReview> GetActionPlanReviewByAPId(System.Int32? aPId)
        {
            var result = actionPlanReviewService.GetActionPlanReviewByAPId(aPId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save ActionPlanReview
        /// </summary>
        /// <param name="actionPlanReview"></param>
        [HttpPost("saveactionplanreview")]
        public ActionResult<System.Boolean> SaveActionPlanReview(ActionPlanReview actionPlanReview)
        {
            var result = actionPlanReviewService.SaveActionPlanReview(actionPlanReview);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update ActionPlanReview
        /// </summary>
        /// <param name="actionPlanReview"></param>
        [HttpPost("updateactionplanreview")]
        public ActionResult<System.Boolean> UpdateActionPlanReview(ActionPlanReview actionPlanReview)
        {
            var result = actionPlanReviewService.UpdateActionPlanReview(actionPlanReview);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete ActionPlanReview By Id aPId
        /// </summary>
        /// <param name="aPId"></param>
        [HttpDelete("{aPId}")]
        public ActionResult<bool> DeleteActionPlanReviewByAPId(System.Int32? aPId)
        {
            var result = actionPlanReviewService.DeleteActionPlanReviewByAPId(aPId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete ActionPlanReview By Multiple ids aPIds
        /// </summary>
        /// <param name="aPIds"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllActionPlanReview(List<int> aPIds)
        {
            var result = actionPlanReviewService.DeleteAllActionPlanReview(aPIds);
            return result;
        }
    }
}
