//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using QAMS.Common.Entities;
    using QAMS.WEB.Entities;
    using QAMS.WEB.Services;
    
    
    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/changecontrolregistration")]
    public class ChangeControlRegistrationController : ControllerBase
    {
        
        private readonly IChangeControlRegistrationService changeControlRegistrationService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="changeControlRegistrationService"></param>
        public ChangeControlRegistrationController(IChangeControlRegistrationService changeControlRegistrationService)
        {
            this.changeControlRegistrationService = changeControlRegistrationService;
        }
        
        /// <summary>
        /// This method is used to Get List of ChangeControlRegistration
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost()]
        public ActionResult<ResponseContext<ChangeControlRegistration>> GetAllChangeControlRegistration(RequestContext requestContext)
        {
            var result = changeControlRegistrationService.GetAllChangeControlRegistration(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get ChangeControlRegistration By Id changeControlId
        /// </summary>
        /// <param name="changeControlId"></param>
        [HttpGet("{changeControlId}")]
        public ActionResult<ChangeControlRegistration> GetChangeControlRegistrationByChangeControlId(System.Int32? changeControlId)
        {
            var result = changeControlRegistrationService.GetChangeControlRegistrationByChangeControlId(changeControlId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save ChangeControlRegistration
        /// </summary>
        /// <param name="changeControlRegistration"></param>
        [HttpPost("savechangecontrolregistration")]

        public ActionResult<bool> SaveChangeControlRegistration(ChangeControlRegistration changeControlRegistration)
        {
            var result = changeControlRegistrationService.SaveChangeControlRegistration(changeControlRegistration);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update ChangeControlRegistration
        /// </summary>
        /// <param name="changeControlRegistration"></param>
        [HttpPost("updatechangecontrolregistration")]
        public ActionResult<bool> UpdateChangeControlRegistration(ChangeControlRegistration changeControlRegistration)
        {
            var result = changeControlRegistrationService.UpdateChangeControlRegistration(changeControlRegistration);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete ChangeControlRegistration By Id changeControlId
        /// </summary>
        /// <param name="changeControlId"></param>
        [HttpDelete("{changeControlId}")]
        public ActionResult<bool> DeleteChangeControlRegistrationByChangeControlId(System.Int32? changeControlId)
        {
            var result = changeControlRegistrationService.DeleteChangeControlRegistrationByChangeControlId(changeControlId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete ChangeControlRegistration By Multiple ids changeControlIds
        /// </summary>
        /// <param name="changeControlIds"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllChangeControlRegistration(List<int> changeControlIds)
        {
            var result = changeControlRegistrationService.DeleteAllChangeControlRegistration(changeControlIds);
            return result;
        }
    }
}
