//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.WEB.API.Extensions
{
    using Microsoft.Extensions.DependencyInjection;
    using QAMS.WEB.Services;
    using QAMS.WEB.Data;
    using VAMLibrary.Core;
    using QAMS.Admin.Services;
    using QAMS.Admin.Data;

    public static class LocalServiceExtention
    {
        
        public static void RegisterLocalServices(this IServiceCollection serviceCollection)
        {
            serviceCollection.AddSingleton<DataAccessHelper>();
            serviceCollection.AddScoped<IChangeControlRegistrationService, ChangeControlRegistrationService>();
            serviceCollection.AddScoped<IChangeControlRegistrationData, ChangeControlRegistrationData>();
            serviceCollection.AddScoped<IMasterDataService, MasterDataService>();
            serviceCollection.AddScoped<IMasterDataData, MasterDataData>();
            serviceCollection.AddScoped<IChangeControlHodApprovalService, ChangeControlHodApprovalService>();
            serviceCollection.AddScoped<IChangeControlHodApprovalData, ChangeControlHodApprovalData>();
            serviceCollection.AddScoped<IChangeContolQaApprovalService, ChangeContolQaApprovalService>();
            serviceCollection.AddScoped<IChangeContolQaApprovalData, ChangeContolQaApprovalData>();
            serviceCollection.AddScoped<IChangeContolActionPlanService, ChangeContolActionPlanService>();
            serviceCollection.AddScoped<IChangeContolActionPlanData, ChangeContolActionPlanData>();
        }
    }
}
