//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Entities;
    using VAMLIbrary.Core.Extentions;
    using QAMS.Common.Entities;
    using QAMS.WEB.Services;


    // Comment
    public static class CFTReviewConverter
    {
        
        public static List<CFTReview> SetAllCFTReview(DataSet dataset)
        {
            try
            {
                List<CFTReview> result = new List<CFTReview>();
                CFTReview cFTReviewData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        cFTReviewData = new CFTReview();
                        cFTReviewData.InitiativeId = DatatypeConverter.SetIntValue(row[CFTReviewConstants.InitiativeId.TrimAt()]);
                        cFTReviewData.InitiativeName = Convert.ToString(row[CFTReviewConstants.InitiativeName.TrimAt()]);
                        cFTReviewData.IsSave = DatatypeConverter.SetBoolValue(row[CFTReviewConstants.IsSave.TrimAt()]);
                        cFTReviewData.Remarks = Convert.ToString(row[CFTReviewConstants.Remarks.TrimAt()]);
                        cFTReviewData.Status = Convert.ToString(row[CFTReviewConstants.Status.TrimAt()]);
                        cFTReviewData.CreatedBy = DatatypeConverter.SetIntValue(row[CFTReviewConstants.CreatedBy.TrimAt()]);
                        cFTReviewData.UpdatedBy = DatatypeConverter.SetIntValue(row[CFTReviewConstants.UpdatedBy.TrimAt()]);
                        cFTReviewData.CreatedDate = DatatypeConverter.SetDateTime(row[CFTReviewConstants.CreatedDate.TrimAt()]);
                        cFTReviewData.UpdatedDate = DatatypeConverter.SetDateTime(row[CFTReviewConstants.UpdatedDate.TrimAt()]);
                        cFTReviewData.Plant = DatatypeConverter.SetIntValue(row[CFTReviewConstants.Plant.TrimAt()]);
                        cFTReviewData.IsProposedChange = DatatypeConverter.SetBoolValue(row[CFTReviewConstants.IsProposedChange.TrimAt()]);
                        cFTReviewData.CFTId = DatatypeConverter.SetIntValue(row[CFTReviewConstants.CFTId.TrimAt()]);
                        cFTReviewData.CFTDocument = Convert.ToString(row[CFTReviewConstants.CFTDocument.TrimAt()]);
                        cFTReviewData.ModifiedBy = Convert.ToString(row[CFTReviewConstants.ModifiedBy.TrimAt()]);
                        cFTReviewData.ModifiedDate = DatatypeConverter.SetDateTime(row[CFTReviewConstants.ModifiedDate.TrimAt()]);
                        result.Add(cFTReviewData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static CFTReview SetCFTReview(DataSet dataset)
        {
            var result = SetAllCFTReview(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
