//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class CFTReviewValidator
    {
        
        public static string IsValidCFTReview(CFTReview cFTReview)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.LengthCheckValidator(cFTReview.InitiativeName,200, nameof(cFTReview.InitiativeName)));
                validationMessages.Append(validationHelper.LengthCheckValidator(cFTReview.Remarks,500, nameof(cFTReview.Remarks)));
                validationMessages.Append(validationHelper.LengthCheckValidator(cFTReview.Status,100, nameof(cFTReview.Status)));
                validationMessages.Append(validationHelper.LengthCheckValidator(cFTReview.CFTDocument,1000, nameof(cFTReview.CFTDocument)));
                validationMessages.Append(validationHelper.LengthCheckValidator(cFTReview.ModifiedBy,100, nameof(cFTReview.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
