//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Extentions;
    using QAMS.Common.Entities;
    
    
    // Comment
    public static class CustomerConverter
    {
        
        public static List<CustomerRegistration> SetAllCustomer(DataSet dataset)
        {
            try
            {
                List<CustomerRegistration> result = new List<CustomerRegistration>();
                CustomerRegistration customerData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        customerData = new CustomerRegistration();
                        customerData.Id = DatatypeConverter.SetIntValue(row[CustomerConstants.Id.TrimAt()]);
                        customerData.name = Convert.ToString(row[CustomerConstants.Name.TrimAt()]);
                        customerData.uniqueCode = Convert.ToString(row[CustomerConstants.Code.TrimAt()]);
                        customerData.contactName = Convert.ToString(row[CustomerConstants.ContactName.TrimAt()]);
                        customerData.address = Convert.ToString(row[CustomerConstants.Address.TrimAt()]);
                        customerData.city = Convert.ToString(row[CustomerConstants.City.TrimAt()]);
                        customerData.state = Convert.ToString(row[CustomerConstants.State.TrimAt()]);
                        customerData.country = Convert.ToString(row[CustomerConstants.Country.TrimAt()]);
                        customerData.zipcode = Convert.ToString(row[CustomerConstants.Zipcode.TrimAt()]);
                        customerData.fax = Convert.ToString(row[CustomerConstants.Fax.TrimAt()]);
                        customerData.email = Convert.ToString(row[CustomerConstants.Email.TrimAt()]);
                        customerData.remark = Convert.ToString(row[CustomerConstants.Remark.TrimAt()]);
                        customerData.createdBy = Convert.ToString(row[CustomerConstants.CreatedBy.TrimAt()]);
                        customerData.CreatedDate = DatatypeConverter.SetDateTime(row[CustomerConstants.CreatedDate.TrimAt()]);
                        customerData.ModifiedBy = Convert.ToString(row[CustomerConstants.ModifiedBy.TrimAt()]);
                        customerData.ModifiedDate = DatatypeConverter.SetDateTime(row[CustomerConstants.ModifiedDate.TrimAt()]);
                        result.Add(customerData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static CustomerRegistration SetCustomer(DataSet dataset)
        {
            var result = SetAllCustomer(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
