//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class CustomerValidator
    {
        
        public static string IsValidCustomer(Customer customer)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(customer.Name, nameof(customer.Name)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.Name,150, nameof(customer.Name)));
                validationMessages.Append(validationHelper.NullCheckValidator(customer.Code, nameof(customer.Code)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.Code,150, nameof(customer.Code)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.ContactName,150, nameof(customer.ContactName)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.Address,250, nameof(customer.Address)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.City,150, nameof(customer.City)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.State,150, nameof(customer.State)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.Country,150, nameof(customer.Country)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.Email,150, nameof(customer.Email)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.Remark,150, nameof(customer.Remark)));
                validationMessages.Append(validationHelper.NullCheckValidator(customer.CreatedBy, nameof(customer.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.CreatedBy,150, nameof(customer.CreatedBy)));
                validationMessages.Append(validationHelper.NullCheckValidator(customer.ModifiedBy, nameof(customer.ModifiedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(customer.ModifiedBy,150, nameof(customer.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
