  CREATE PROCEDURE [dbo].[USP_QADecision_PSY_DELETE_ALL] @QADId_PSY nvarchar(max)  
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[QADecision_PSY] WHERE [QADId_PSY] IN (select value from STRING_SPLIT(@QADId_PSY, ',')) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END