  CREATE PROCEDURE [dbo].[USP_newdocument_PSY_DELETE] @nd_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[newdocument_PSY]  WHERE [nd_PSY] IN (@nd_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END