  CREATE PROCEDURE [dbo].[USP_QADecision_PSY_DELETE] @QADId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[QADecision_PSY]  WHERE [QADId_PSY] IN (@QADId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END