  CREATE PROCEDURE [dbo].[USP_CustomerNotification_PSY_DELETE] @CNId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[CustomerNotification_PSY]  WHERE [CNId_PSY] IN (@CNId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END