CREATE PROCEDURE [dbo].[USP_MASTER_DATA]
AS
BEGIN

DECLARE @ROLE_ID INT=0,@USER_ID INT=0;

IF EXISTS(SELECT 1 FROM dbo.MASTER_CATEGORY_CTG)
BEGIN
DELETE FROM dbo.MASTER_CATEGORY_CTG
END

INSERT dbo.MASTER_CATEGORY_CTG(ID_CTG,NAME_CTG,DISPLAY_NAME_CTG) VALUES(1,'CHANGECONTROLS','CHANGE CONTROLS')
INSERT dbo.MASTER_CATEGORY_CTG(ID_CTG,NAME_CTG,DISPLAY_NAME_CTG) VALUES(2,'Deviations','Deviations')
INSERT dbo.MASTER_CATEGORY_CTG(ID_CTG,NAME_CTG,DISPLAY_NAME_CTG) VALUES(3,'CAPA','Correction and Preventive Actions')


IF EXISTS(SELECT 1 FROM dbo.CATEGORY_CTG)
BEGIN
DELETE FROM dbo.CATEGORY_CTG
END
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(1,'ControlLoginInitiation','Control Login Initiation')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(2,'HODReview','HOD Review')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(3,'QAReview','QA Review')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(4,'CFTReview','CFT Review')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(5,'CustomerNotification','Customer Notification')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(6,'QADecision','QA Decision')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(7,'ActionPlan','Action Plan')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(8,'FinalClosure','Final Closure')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(9,'ExtensionofTargetDate','Extension of Target Date')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(10,'WorkTransfer','Work Transfer')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(11,'DossierPrint','Dossier Print')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(12,'AuditTrials','Audit Trials')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(13,'Reports','Reports')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(14,'DeviationInitiation','Deviation Initiation')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(15,'Investigation','Investigation')
INSERT dbo.CATEGORY_CTG(NAME_CTG,DISPLAY_NAME_CTG) VALUES(16,'CAPAInitiation','CAPA Initiation')


IF NOT EXISTS(SELECT 1 FROM dbo.Role_PSY)
BEGIN

INSERT dbo.Role_PSY(Name_PSY,Description_PSY,CreatedBy_PSY,ModifiedBy_PSY,CreatedDate_PSY,ModifiedDate_PSY)
VALUES ('adminrole','admin role','admin','admin',GETDATE(),GETDATE())
SELECT  @ROLE_ID=@@IDENTITY;

INSERT dbo.USERS_ROLE_MAPPING(ROLE_ID,ID_CTG)
SELECT @ROLE_ID, ID_CTG FROM CATEGORY_CTG

END

IF NOT EXISTS(SELECT 1 FROM dbo.User_PSY WHERE USER='ADMIN')
BEGIN
INSERT dbo.User_PSY (FirstName_PSY,LastName_PSY,UserId_PSY,RoleId_PSY,Plants_PSY,Password_PSY)
VALUES('admin''admin','admin',@ROLE_ID,'Plant A','Passw0rd')
SELECT @USER_ID=@@IDENTITY;
END

END