  CREATE PROCEDURE [dbo].[USP_FunctionalProfile_PSY_UPDATE] @Id_PSY int,
@RoleId_PSY Int,
@ChangeControlInitiation_PSY Bit,
@CCHODReview_PSY Bit,
@CCQAReview_PSY Bit,
@CCCFTReview_PSY Bit,
@CCCustomerNotification_PSY Bit,
@CCQADecision_PSY Bit,
@CCActionPlan_PSY Bit,
@CCFinalClosure_PSY Bit,
@CCExtensionOfTargetDate_PSY Bit,
@CCWorkTransfer_PSY Bit,
@CCDossierPrint_PSY Bit,
@CCAuditTrial_PSY Bit,
@CCReport_PSY Bit,
@DeviationInitiation_PSY Bit,
@DIHODReview_PSY Bit,
@DIQAReview_PSY Bit,
@DICFTReview_PSY Bit,
@DICustomerNotification_PSY Bit,
@QAManager_PSY Bit,
@Investigation_PSY Bit,
@DIQADecision_PSY Bit,
@DIActionPlan_PSY Bit,
@DIFinalClosure_PSY Bit,
@DIExtensionOfTargetDate_PSY Bit,
@DIWorkTransfer_PSY Bit,
@DIDossierPrint_PSY Bit,
@DIAuditTrial_PSY Bit,
@DIReport_PSY Bit,
@CAPAInitiation_PSY Bit,
@CAPAHODReview_PSY Bit,
@CAPAQAReview_PSY Bit,
@CAPACFTReview_PSY Bit,
@CAPAQADecision_PSY Bit,
@CAPAActionPlan_PSY Bit,
@CAPAFinalClosure_PSY Bit,
@CAPAExtensionOfTargetDate_PSY Bit,
@CAPAWorkTransfer_PSY Bit,
@CAPADossierPrint_PSY Bit,
@CAPAAuditTrial_PSY Bit,
@CAPAReport_PSY Bit,
@SecuritySetting_PSY Bit,
@NewRole_PSY Bit,
@SetFunctionalProfile_PSY Bit,
@NewUser_PSY Bit,
@NewUserApproval_PSY Bit,
@PlantAssignment_PSY Bit,
@ModifyPlantAssignment_PSY Bit,
@UserGroup_PSY Bit,
@ModifyUserGroup_PSY Bit,
@UserAccountStatus_PSY Bit,
@ResetLoginPassword_PSY Bit,
@ModifyUser_PSY Bit,
@ProductOrMaterialRegistration_PSY Bit,
@BatchOrLotParticulars_PSY Bit,
@EquipmentRegistration_PSY Bit,
@MarketRegistration_PSY Bit,
@CustomerRegistration_PSY Bit,
@AuditTrial_PSY Bit,
@Remark_PSY NVarChar(150),
@ModifiedBy_PSY NVarChar(150) 
 AS 
 BEGIN 
  BEGIN TRY 
  
 UPDATE [dbo].[FunctionalProfile_PSY] SET 
RoleId_PSY=@RoleId_PSY,
ChangeControlInitiation_PSY=@ChangeControlInitiation_PSY,
CCHODReview_PSY=@CCHODReview_PSY,
CCQAReview_PSY=@CCQAReview_PSY,
CCCFTReview_PSY=@CCCFTReview_PSY,
CCCustomerNotification_PSY=@CCCustomerNotification_PSY,
CCQADecision_PSY=@CCQADecision_PSY,
CCActionPlan_PSY=@CCActionPlan_PSY,
CCFinalClosure_PSY=@CCFinalClosure_PSY,
CCExtensionOfTargetDate_PSY=@CCExtensionOfTargetDate_PSY,
CCWorkTransfer_PSY=@CCWorkTransfer_PSY,
CCDossierPrint_PSY=@CCDossierPrint_PSY,
CCAuditTrial_PSY=@CCAuditTrial_PSY,
CCReport_PSY=@CCReport_PSY,
DeviationInitiation_PSY=@DeviationInitiation_PSY,
DIHODReview_PSY=@DIHODReview_PSY,
DIQAReview_PSY=@DIQAReview_PSY,
DICFTReview_PSY=@DICFTReview_PSY,
DICustomerNotification_PSY=@DICustomerNotification_PSY,
QAManager_PSY=@QAManager_PSY,
Investigation_PSY=@Investigation_PSY,
DIQADecision_PSY=@DIQADecision_PSY,
DIActionPlan_PSY=@DIActionPlan_PSY,
DIFinalClosure_PSY=@DIFinalClosure_PSY,
DIExtensionOfTargetDate_PSY=@DIExtensionOfTargetDate_PSY,
DIWorkTransfer_PSY=@DIWorkTransfer_PSY,
DIDossierPrint_PSY=@DIDossierPrint_PSY,
DIAuditTrial_PSY=@DIAuditTrial_PSY,
DIReport_PSY=@DIReport_PSY,
CAPAInitiation_PSY=@CAPAInitiation_PSY,
CAPAHODReview_PSY=@CAPAHODReview_PSY,
CAPAQAReview_PSY=@CAPAQAReview_PSY,
CAPACFTReview_PSY=@CAPACFTReview_PSY,
CAPAQADecision_PSY=@CAPAQADecision_PSY,
CAPAActionPlan_PSY=@CAPAActionPlan_PSY,
CAPAFinalClosure_PSY=@CAPAFinalClosure_PSY,
CAPAExtensionOfTargetDate_PSY=@CAPAExtensionOfTargetDate_PSY,
CAPAWorkTransfer_PSY=@CAPAWorkTransfer_PSY,
CAPADossierPrint_PSY=@CAPADossierPrint_PSY,
CAPAAuditTrial_PSY=@CAPAAuditTrial_PSY,
CAPAReport_PSY=@CAPAReport_PSY,
SecuritySetting_PSY=@SecuritySetting_PSY,
NewRole_PSY=@NewRole_PSY,
SetFunctionalProfile_PSY=@SetFunctionalProfile_PSY,
NewUser_PSY=@NewUser_PSY,
NewUserApproval_PSY=@NewUserApproval_PSY,
PlantAssignment_PSY=@PlantAssignment_PSY,
ModifyPlantAssignment_PSY=@ModifyPlantAssignment_PSY,
UserGroup_PSY=@UserGroup_PSY,
ModifyUserGroup_PSY=@ModifyUserGroup_PSY,
UserAccountStatus_PSY=@UserAccountStatus_PSY,
ResetLoginPassword_PSY=@ResetLoginPassword_PSY,
ModifyUser_PSY=@ModifyUser_PSY,
ProductOrMaterialRegistration_PSY=@ProductOrMaterialRegistration_PSY,
BatchOrLotParticulars_PSY=@BatchOrLotParticulars_PSY,
EquipmentRegistration_PSY=@EquipmentRegistration_PSY,
MarketRegistration_PSY=@MarketRegistration_PSY,
CustomerRegistration_PSY=@CustomerRegistration_PSY,
AuditTrial_PSY=@AuditTrial_PSY,
Remark_PSY=@Remark_PSY,
ModifiedBy_PSY=@ModifiedBy_PSY WHERE  [Id_PSY] = @Id_PSY ;  select @Id_PSY; 
  
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END 