  CREATE PROCEDURE [dbo].[USP_HODReview_PSY_DELETE] @HodId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[HODReview_PSY]  WHERE [HodId_PSY] IN (@HodId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END