  CREATE PROCEDURE [dbo].[USP_CFTReview_PSY_DELETE] @CFTId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[CFTReview_PSY]  WHERE [CFTId_PSY] IN (@CFTId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END