  CREATE PROCEDURE [dbo].[USP_CFTReview_PSY_DELETE_ALL] @CFTId_PSY nvarchar(max)  
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[CFTReview_PSY] WHERE [CFTId_PSY] IN (select value from STRING_SPLIT(@CFTId_PSY, ',')) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END