  CREATE PROCEDURE [dbo].[USP_Closure_PSY_DELETE] @CId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[Closure_PSY]  WHERE [CId_PSY] IN (@CId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END