//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class QAReviewConstants
    {
        
        public const string ClassificationOfChange = "@ClassificationOfChange_PSY";
        
        public const string ImpactOnProcFormats = "@ImpactOnProcFormats_PSY";
        
        public const string ProcedureFormat = "@ProcedureFormat_PSY";
        
        public const string IsRegularCustomer = "@IsRegularCustomer_PSY";
        
        public const string ImpactCommitment = "@ImpactCommitment_PSY";
        
        public const string ReviewComments = "@ReviewComments_PSY";
        
        public const string InitiativeId = "@InitiativeId_PSY";
        
        public const string InitiativeName = "@InitiativeName_PSY";
        
        public const string IsSave = "@IsSave_PSY";
        
        public const string Status = "@Status_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string UpdatedBy = "@UpdatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string UpdatedDate = "@UpdatedDate_PSY";
        
        public const string Plant = "@Plant_PSY";
        
        public const string QAId = "@QAId_PSY";
        
        public const string QaDocument = "@QaDocument_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_QAReview_PSY_GET_ALL = "dbo.USP_QAReview_PSY_GET_ALL";
        
        public const string USP_QAReview_PSY_GET = "dbo.USP_QAReview_PSY_GET";
        
        public const string USP_QAReview_PSY_INSERT = "dbo.USP_QAReview_PSY_INSERT";
        
        public const string USP_QAReview_PSY_UPDATE = "dbo.USP_QAReview_PSY_UPDATE";
        
        public const string USP_QAReview_PSY_DELETE = "dbo.USP_QAReview_PSY_DELETE";
        
        public const string USP_QAReview_PSY_DELETE_ALL = "dbo.USP_QAReview_PSY_DELETE_ALL";
        
        public const string USP_QuickQAReview_INSERT = "dbo.USP_QuickQAReview_INSERT";
        
        public const string USP_QuickQAReview_UPDATE = "dbo.USP_QuickQAReview_UPDATE";
    }
}
