//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    using QAMS.Common.Entities;


    // Comment
    public class Department
    {

        //private System.Int32? idField;



        public System.Int32? id { get; set; }



        public string departmentName { get; set; }


        public string departmentCode { get; set; }


        public string initiatedBy { get; set; }


        public DateTime? date { get; set; }


        public string modifiedBy { get; set; }

        public DateTime? modifiedDate { get; set; }

    }
}
