//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class DepartmentConstants
    {
        
        public const string Id = "@Id_PSY";
        
        public const string Name = "@Name_PSY";
        
        public const string Code = "@Code_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_Department_PSY_GET_ALL = "dbo.USP_Department_PSY_GET_ALL";
        
        public const string USP_Department_PSY_GET = "dbo.USP_Department_PSY_GET";
        
        public const string USP_Department_PSY_INSERT = "dbo.USP_Department_PSY_INSERT";
        
        public const string USP_Department_PSY_UPDATE = "dbo.USP_Department_PSY_UPDATE";
        
        public const string USP_Department_PSY_DELETE = "dbo.USP_Department_PSY_DELETE";
        
        public const string USP_Department_PSY_DELETE_ALL = "dbo.USP_Department_PSY_DELETE_ALL";
        
        public const string USP_QuickDepartment_INSERT = "dbo.USP_QuickDepartment_INSERT";
        
        public const string USP_QuickDepartment_UPDATE = "dbo.USP_QuickDepartment_UPDATE";
    }
}
