//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Common.Entities;
    using QAMS.Entities;
    using VAMLibrary.Core;
    using VAMLibrary.Core.Common;
    
    
    // Comment
    public class HODReviewData : IHODReviewData
    {
        
        private readonly DataAccessHelper dataAccessHelper;
        
        public HODReviewData(DataAccessHelper dataAccessHelper)
        {
            this.dataAccessHelper = dataAccessHelper;
        }
        
        public DataSet GetAllHODReview(RequestContext requestContext)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = RequestContextConstants.PageNumber, Value = requestContext.PageNumber });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = RequestContextConstants.PageSize, Value = requestContext.PageSize });
                DataSet dataset = (DataSet)dataAccessHelper.ExecuteStoredProcedure(HODReviewConstants.USP_HODReview_PSY_GET_ALL, sqlparms, ExecutionType.Dataset);
                return dataset;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public DataSet GetHODReviewByHodId(System.Int32? hodId)
        {
            try
            {
                DataSet dataset = (DataSet)dataAccessHelper.ExecuteStoredProcedure(HODReviewConstants.USP_HODReview_PSY_GET, HODReviewConstants.HodId, DbType.Int32, hodId, ExecutionType.Dataset);
                return dataset;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }

        public DataSet GetHODReviewByInit(System.Int32? initId)
        {
            try
            {
                DataSet dataset = (DataSet)dataAccessHelper.ExecuteStoredProcedure("dbo.USP_HODReview_PSY_GET_BY_INIT", "@Init_PSY", DbType.Int32, initId, ExecutionType.Dataset);
                return dataset;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }

        public bool SaveHODReview(HODReview hODReview)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.InitiativeId, Value = hODReview.InitiativeId });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.InitiativeName, Value = hODReview.InitiativeName });
                sqlparms.Add(new SqlParameter { DbType = DbType.Boolean, ParameterName = HODReviewConstants.IsSave, Value = hODReview.IsSave });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.Comments, Value = hODReview.Comments });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.Status, Value = hODReview.Status });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.CreatedBy, Value = hODReview.CreatedBy });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.UpdatedBy, Value = hODReview.UpdatedBy });
                sqlparms.Add(new SqlParameter { DbType = DbType.DateTime, ParameterName = HODReviewConstants.UpdatedDate, Value = hODReview.UpdatedDate });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.Plant, Value = hODReview.Plant });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.HODDocument, Value = hODReview.HODDocument });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.ModifiedBy, Value = hODReview.ModifiedBy });
                Object result = dataAccessHelper.ExecuteStoredProcedure(HODReviewConstants.USP_HODReview_PSY_INSERT, sqlparms, ExecutionType.Scalar);
                return (Convert.ToInt32(result) > 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool UpdateHODReview(HODReview hODReview)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.HodId, Value = hODReview.HodId });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.InitiativeId, Value = hODReview.InitiativeId });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.InitiativeName, Value = hODReview.InitiativeName });
                sqlparms.Add(new SqlParameter { DbType = DbType.Boolean, ParameterName = HODReviewConstants.IsSave, Value = hODReview.IsSave });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.Comments, Value = hODReview.Comments });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.Status, Value = hODReview.Status });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.UpdatedBy, Value = hODReview.UpdatedBy });
                sqlparms.Add(new SqlParameter { DbType = DbType.DateTime, ParameterName = HODReviewConstants.UpdatedDate, Value = hODReview.UpdatedDate });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = HODReviewConstants.Plant, Value = hODReview.Plant });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.HODDocument, Value = hODReview.HODDocument });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = HODReviewConstants.ModifiedBy, Value = hODReview.ModifiedBy });
                Object result = dataAccessHelper.ExecuteStoredProcedure(HODReviewConstants.USP_HODReview_PSY_UPDATE, sqlparms, ExecutionType.Scalar);
                return (Convert.ToInt32(result) > 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteHODReviewByHodId(System.Int32? hodId)
        {
            try
            {
                var result = dataAccessHelper.ExecuteStoredProcedure(HODReviewConstants.USP_HODReview_PSY_DELETE, HODReviewConstants.HodId, DbType.Int32, hodId, ExecutionType.NonQuery);
                return (Convert.ToInt32(result) >= 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllHODReview(List<int> hodIds)
        {
            try
            {
                var result = dataAccessHelper.ExecuteStoredProcedure(HODReviewConstants.USP_HODReview_PSY_DELETE_ALL, HODReviewConstants.HodId, DbType.String, string.Join(',',  hodIds), ExecutionType.NonQuery);
                return (Convert.ToInt32(result) >= 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
