//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Common.Entities;
    using QAMS.Entities;
    
    
    // Comment
    public interface IHODReviewData
    {
        
        DataSet GetAllHODReview(RequestContext requestContext);
        
        DataSet GetHODReviewByHodId(System.Int32? hodId);
        
        bool SaveHODReview(HODReview hODReview);
        
        bool UpdateHODReview(HODReview hODReview);
        
        bool DeleteHODReviewByHodId(System.Int32? hodId);
        
        bool DeleteAllHODReview(List<int> hodIds);
    }
}
