//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Extentions;
    using QAMS.Common.Entities;
    
    
    // Comment
    public static class SecuritySettingConverter
    {
        
        public static List<SecuritySetting> SetAllSecuritySetting(DataSet dataset)
        {
            try
            {
                List<SecuritySetting> result = new List<SecuritySetting>();
                SecuritySetting securitySettingData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        securitySettingData = new SecuritySetting();
                        securitySettingData.Id = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.Id.TrimAt()]);
                        securitySettingData.MinimumUserIdLength = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.MinimumUserIdLength.TrimAt()]);
                        securitySettingData.MinimumPasswordLength = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.MinimumPasswordLength.TrimAt()]);
                        securitySettingData.MaximumTenureOfPassword = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.MaximumTenureOfPassword.TrimAt()]);
                        securitySettingData.PasswordExpiryAlert = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.PasswordExpiryAlert.TrimAt()]);
                        securitySettingData.RetainHistoryOfLastPassword = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.RetainHistoryOfLastPassword.TrimAt()]);
                        securitySettingData.ComplexityofPassword = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.ComplexityofPassword.TrimAt()]);
                        securitySettingData.AccountLockout = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.AccountLockout.TrimAt()]);
                        securitySettingData.SessionTimeout = DatatypeConverter.SetIntValue(row[SecuritySettingConstants.SessionTimeout.TrimAt()]);
                        securitySettingData.Remark = Convert.ToString(row[SecuritySettingConstants.Remark.TrimAt()]);
                        securitySettingData.CreatedBy = Convert.ToString(row[SecuritySettingConstants.CreatedBy.TrimAt()]);
                        securitySettingData.CreatedDate = DatatypeConverter.SetDateTime(row[SecuritySettingConstants.CreatedDate.TrimAt()]);
                        securitySettingData.ModifiedBy = Convert.ToString(row[SecuritySettingConstants.ModifiedBy.TrimAt()]);
                        securitySettingData.ModifiedDate = DatatypeConverter.SetDateTime(row[SecuritySettingConstants.ModifiedDate.TrimAt()]);
                        result.Add(securitySettingData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static SecuritySetting SetSecuritySetting(DataSet dataset)
        {
            var result = SetAllSecuritySetting(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
