//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class SecuritySettingValidator
    {
        
        public static string IsValidSecuritySetting(SecuritySetting securitySetting)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(securitySetting.Remark, nameof(securitySetting.Remark)));
                validationMessages.Append(validationHelper.LengthCheckValidator(securitySetting.Remark,150, nameof(securitySetting.Remark)));
                validationMessages.Append(validationHelper.NullCheckValidator(securitySetting.CreatedBy, nameof(securitySetting.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(securitySetting.CreatedBy,150, nameof(securitySetting.CreatedBy)));
                validationMessages.Append(validationHelper.NullCheckValidator(securitySetting.ModifiedBy, nameof(securitySetting.ModifiedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(securitySetting.ModifiedBy,150, nameof(securitySetting.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
