//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;


    // Comment
    public class UserGroup
    {
        
       
        
        public System.Int32? id { get; set; }
        
        
        public string name { get; set; }
       

        public string code { get; set; }
      
        
        public string roles { get;set; }
     
        
        public string revision { get; set; }
     
        
        public string createdBy { get; set; }
     
        
        public DateTime? createdDate { get; set; }
      
        
        public string modifiedBy { get; set; }
       
        
        public DateTime? modifiedDate { get; set; }

        public string remarks { get; set; }

        public List<User> selectedUsers { get; set; }

        //public UserMapping UserMapping { get; set; }
        public string userMetdata { get; set; }
       
    }

    public class UserMapping
    {
        public System.Int32? id { get; set; } = 0;

        public string name { get; set; }
    }
}
