//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    using QAMS.Common.Entities;


    // Comment
    public class CustomerRegistration
    {
       
        public System.Int32? Id { get; set; }
        public string name { get; set; }
        public string uniqueCode { get; set; }
        public string contactName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
        public string createdBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}
