//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class CustomerConstants
    {
        
        public const string Id = "@Id_PSY";
        
        public const string Name = "@Name_PSY";
        
        public const string Code = "@Code_PSY";
        
        public const string ContactName = "@ContactName_PSY";
        
        public const string Address = "@Address_PSY";
        
        public const string City = "@City_PSY";
        
        public const string State = "@State_PSY";
        
        public const string Country = "@Country_PSY";
        
        public const string Zipcode = "@Zipcode_PSY";
        
        public const string Fax = "@Fax_PSY";
        
        public const string Email = "@Email_PSY";
        
        public const string Remark = "@Remark_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_Customer_PSY_GET_ALL = "dbo.USP_Customer_PSY_GET_ALL";
        
        public const string USP_Customer_PSY_GET = "dbo.USP_Customer_PSY_GET";
        
        public const string USP_Customer_PSY_INSERT = "dbo.USP_Customer_PSY_INSERT";
        
        public const string USP_Customer_PSY_UPDATE = "dbo.USP_Customer_PSY_UPDATE";
        
        public const string USP_Customer_PSY_DELETE = "dbo.USP_Customer_PSY_DELETE";
        
        public const string USP_Customer_PSY_DELETE_ALL = "dbo.USP_Customer_PSY_DELETE_ALL";
        
        public const string USP_QuickCustomer_INSERT = "dbo.USP_QuickCustomer_INSERT";
        
        public const string USP_QuickCustomer_UPDATE = "dbo.USP_QuickCustomer_UPDATE";
    }
}
