//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Admin.Entities;
    using VAMLIbrary.Core.Extentions;
    using QAMS.Common.Entities;
    
    
    // Comment
    public static class PlantConverter
    {
        
        public static List<Plant> SetAllPlant(DataSet dataset)
        {
            try
            {
                List<Plant> result = new List<Plant>();
                Plant plantData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        plantData = new Plant();
                        plantData.id = DatatypeConverter.SetIntValue(row[PlantConstants.Id.TrimAt()]);
                        plantData.name = Convert.ToString(row[PlantConstants.Name.TrimAt()]);
                        plantData.code = Convert.ToString(row[PlantConstants.Code.TrimAt()]);
                        plantData.revision = DatatypeConverter.SetIntValue(row[PlantConstants.Revision.TrimAt()]);
                        plantData.address = Convert.ToString(row[PlantConstants.Address.TrimAt()]);
                        plantData.comment = Convert.ToString(row[PlantConstants.Comment.TrimAt()]);
                        plantData.createdBy = Convert.ToString(row[PlantConstants.CreatedBy.TrimAt()]);
                        plantData.createdDate = DatatypeConverter.SetDateTime(row[PlantConstants.CreatedDate.TrimAt()]);
                        plantData.ModifiedBy = Convert.ToString(row[PlantConstants.ModifiedBy.TrimAt()]);
                        plantData.ModifiedDate = DatatypeConverter.SetDateTime(row[PlantConstants.ModifiedDate.TrimAt()]);
                        result.Add(plantData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static Plant SetPlant(DataSet dataset)
        {
            var result = SetAllPlant(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
