//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    // Comment
    public class worktransferregistrationoinitiation
    {
        
        private System.Int32? wtriidField;
        
        private string worktransferdescriptionField;
        
        private string worktransferfromField;
        
        private string tasklistField;
        
        private string worktransfertoField;
        
        private DateTime? validuptoField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public System.Int32? wtriid
        {
            get
            {
                return this.wtriidField;
            }
            set
            {
                this.wtriidField = value;
            }
        }
        
        public string worktransferdescription
        {
            get
            {
                return this.worktransferdescriptionField;
            }
            set
            {
                this.worktransferdescriptionField = value;
            }
        }
        
        public string worktransferfrom
        {
            get
            {
                return this.worktransferfromField;
            }
            set
            {
                this.worktransferfromField = value;
            }
        }
        
        public string tasklist
        {
            get
            {
                return this.tasklistField;
            }
            set
            {
                this.tasklistField = value;
            }
        }
        
        public string worktransferto
        {
            get
            {
                return this.worktransfertoField;
            }
            set
            {
                this.worktransfertoField = value;
            }
        }
        
        public DateTime? validupto
        {
            get
            {
                return this.validuptoField;
            }
            set
            {
                this.validuptoField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
