//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Admin.Entities
{
    using System;
    using System.Collections.Generic;
    using QAMS.Common.Entities;
    
    
    // Comment
    public class SecuritySetting
    {
        
        private System.Int32? idField;
        
        private System.Int32? minimumuseridlengthField;
        
        private System.Int32? minimumpasswordlengthField;
        
        private System.Int32? maximumtenureofpasswordField;
        
        private System.Int32? passwordexpiryalertField;
        
        private System.Int32? retainhistoryoflastpasswordField;
        
        private System.Int32? complexityofpasswordField;
        
        private System.Int32? accountlockoutField;
        
        private System.Int32? sessiontimeoutField;
        
        private string remarkField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public System.Int32? Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        public System.Int32? MinimumUserIdLength
        {
            get
            {
                return this.minimumuseridlengthField;
            }
            set
            {
                this.minimumuseridlengthField = value;
            }
        }
        
        public System.Int32? MinimumPasswordLength
        {
            get
            {
                return this.minimumpasswordlengthField;
            }
            set
            {
                this.minimumpasswordlengthField = value;
            }
        }
        
        public System.Int32? MaximumTenureOfPassword
        {
            get
            {
                return this.maximumtenureofpasswordField;
            }
            set
            {
                this.maximumtenureofpasswordField = value;
            }
        }
        
        public System.Int32? PasswordExpiryAlert
        {
            get
            {
                return this.passwordexpiryalertField;
            }
            set
            {
                this.passwordexpiryalertField = value;
            }
        }
        
        public System.Int32? RetainHistoryOfLastPassword
        {
            get
            {
                return this.retainhistoryoflastpasswordField;
            }
            set
            {
                this.retainhistoryoflastpasswordField = value;
            }
        }
        
        public System.Int32? ComplexityofPassword
        {
            get
            {
                return this.complexityofpasswordField;
            }
            set
            {
                this.complexityofpasswordField = value;
            }
        }
        
        public System.Int32? AccountLockout
        {
            get
            {
                return this.accountlockoutField;
            }
            set
            {
                this.accountlockoutField = value;
            }
        }
        
        public System.Int32? SessionTimeout
        {
            get
            {
                return this.sessiontimeoutField;
            }
            set
            {
                this.sessiontimeoutField = value;
            }
        }
        
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
