//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Entities;
    using VAMLIbrary.Core.Validators;
    
    
    // Comment
    public static class HODReviewValidator
    {
        
        public static string IsValidHODReview(HODReview hODReview)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.LengthCheckValidator(hODReview.InitiativeName,200, nameof(hODReview.InitiativeName)));
                validationMessages.Append(validationHelper.LengthCheckValidator(hODReview.Comments,500, nameof(hODReview.Comments)));
                validationMessages.Append(validationHelper.LengthCheckValidator(hODReview.Status,100, nameof(hODReview.Status)));
                validationMessages.Append(validationHelper.LengthCheckValidator(hODReview.HODDocument,0, nameof(hODReview.HODDocument)));
                validationMessages.Append(validationHelper.LengthCheckValidator(hODReview.ModifiedBy,100, nameof(hODReview.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
