//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAMS.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using QAMS.Entities;
    using VAMLIbrary.Core.Extentions;
    using QAMS.Common.Entities;
    using QAMS.WEB.Services;


    // Comment
    public static class HODReviewConverter
    {
        
        public static List<HODReview> SetAllHODReview(DataSet dataset)
        {
            try
            {
                List<HODReview> result = new List<HODReview>();
                HODReview hODReviewData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        hODReviewData = new HODReview();
                        hODReviewData.InitiativeId = DatatypeConverter.SetIntValue(row[HODReviewConstants.InitiativeId.TrimAt()]);
                        hODReviewData.InitiativeName = Convert.ToString(row[HODReviewConstants.InitiativeName.TrimAt()]);
                        hODReviewData.IsSave = DatatypeConverter.SetBoolValue(row[HODReviewConstants.IsSave.TrimAt()]);
                        hODReviewData.Comments = Convert.ToString(row[HODReviewConstants.Comments.TrimAt()]);
                        hODReviewData.Status = Convert.ToString(row[HODReviewConstants.Status.TrimAt()]);
                        hODReviewData.CreatedBy = DatatypeConverter.SetIntValue(row[HODReviewConstants.CreatedBy.TrimAt()]);
                        hODReviewData.UpdatedBy = DatatypeConverter.SetIntValue(row[HODReviewConstants.UpdatedBy.TrimAt()]);
                        hODReviewData.CreatedDate = DatatypeConverter.SetDateTime(row[HODReviewConstants.CreatedDate.TrimAt()]);
                        hODReviewData.UpdatedDate = DatatypeConverter.SetDateTime(row[HODReviewConstants.UpdatedDate.TrimAt()]);
                        hODReviewData.Plant = DatatypeConverter.SetIntValue(row[HODReviewConstants.Plant.TrimAt()]);
                        hODReviewData.HodId = DatatypeConverter.SetIntValue(row[HODReviewConstants.HodId.TrimAt()]);
                        hODReviewData.HODDocument = Convert.ToString(row[HODReviewConstants.HODDocument.TrimAt()]);
                        hODReviewData.ModifiedBy = Convert.ToString(row[HODReviewConstants.ModifiedBy.TrimAt()]);
                        hODReviewData.ModifiedDate = DatatypeConverter.SetDateTime(row[HODReviewConstants.ModifiedDate.TrimAt()]);
                        result.Add(hODReviewData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static HODReview SetHODReview(DataSet dataset)
        {
            var result = SetAllHODReview(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
